### ISSUE TITLE
Incorporate file importing into schema spec

### ISSUE THREAD

**Issue by schickling** [prisma/specs#10]
From [Notion doc](https://www.notion.so/prismaio/Import-3d55827ee14b4516a354da05107dcc73):

![image](https://user-images.githubusercontent.com/1567498/60672014-aef1fc00-9e74-11e9-9b56-e8f985b3fc39.png)

**Comment by matthewmueller** [comment]
Updated: https://github.com/prisma/specs/tree/master/prisma-schema#importing-schemas
