### ISSUE TITLE
Apply area labels to PRs

### ISSUE THREAD

**Issue by janpio** [prisma/specs#100]
I just went through all PRs in the specs repo and tried to apply the area/* labels.
Some I didn't really know what to do, and need your help @divyenduz @schickling @matthewmueller 

https://github.com/prisma/specs/pulls?q=is%3Apr+no%3Alabel

Binaries:
https://github.com/prisma/specs/pull/70
https://github.com/prisma/specs/pull/33
https://github.com/prisma/specs/pull/29
https://github.com/prisma/specs/pull/24

Capabilities:
https://github.com/prisma/specs/pull/68
https://github.com/prisma/specs/pull/38

Errors:
https://github.com/prisma/specs/pull/43
https://github.com/prisma/specs/pull/17

Query Capabilities:
https://github.com/prisma/specs/pull/15

It is very possible we are missing the proper label for some of those, if so please let me know and we will see if we should create some more labels.

**Comment by matthewmueller** [comment]
applied labels to open issues

**Comment by janpio** [comment]
Thanks, please also do the already closed/merged ones as it will help to understand the bigger context of those.

**Comment by schickling** [comment]
Done. ✅
