### ISSUE TITLE
Apply area labels to issues

### ISSUE THREAD

**Issue by janpio** [prisma/specs#101]
Misc:
https://github.com/prisma/specs/issues/95
https://github.com/prisma/specs/issues/93
https://github.com/prisma/specs/issues/72
https://github.com/prisma/specs/issues/7

Errors:
https://github.com/prisma/specs/issues/42
https://github.com/prisma/specs/issues/3

Query Capabilities:
https://github.com/prisma/specs/issues/8

Binaries:
https://github.com/prisma/specs/issues/2
https://github.com/prisma/specs/issues/1

**Comment by matthewmueller** [comment]
Applied the labels I knew of.

@schickling please clarify and label: https://github.com/prisma/specs/issues/7

**Comment by janpio** [comment]
#1 is also missing a label, which please should be applied although it is already closed.
