### ISSUE TITLE
Printing `prisma2 dev` as the first instruction after `init` is problematic

### ISSUE THREAD

**Issue by nikolasburk** [prisma/specs#108]
After having finished the `prisma2 init` flow, we _always_ print `prisma2 dev` as the first instruction to be executed in the `Next steps` section of the success screen.

This is problematic because the success screen sometimes contains further info (e.g. for starter kits, it often includes the `npm start` command as well). If a user executes `prisma2 dev`, the `Next steps` section will be lost forever and they have no more hints what else to do with the starter kit.

**Comment by schickling** [comment]
This will be alleviated by https://github.com/prisma/studio/issues/78
