### ISSUE TITLE
Schema capability spec

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#110]
Ongoing work: https://github.com/prisma/specs/pull/68

https://github.com/prisma/specs/blob/caps/caps/Readme.md#schema-capabilities

**Comment by matthewmueller** [comment]
This is still ongoing. Once I've wrapped up the Lift prototype, I should have a clear picture of how to write this spec.

**Comment by matthewmueller** [comment]
I didn't have time to continue working on this and it doesn't look like I'll have a chance to finish this until we resolve some more immediate specs for engineering. 

I feel very confident that if we get capabilities right, we're setting ourselves up for success. I'd like to get back to this once there's a bit more slack.

**Comment by divyenduz** [comment]
Internal note: Important but dropping for now because priority

**Comment by Errorname** [comment]
Just checking: Is it still de-prioritised? And can we expect this for the GA of photon or after?

**Comment by divyenduz** [comment]
Let me try to get that answered internally 🙏

**Comment by Errorname** [comment]
@divyenduz Thank you! (I forgot to mention that was interesting in this issue because it's a dependance of this one: https://github.com/prisma/photonjs/issues/184 )

**Comment by matthewmueller** [comment]
Note: unassigning myself on things I'm not actively working on. I may pick this up in the future.

**Comment by janpio** [comment]
Closing because caps work is finished.
