### ISSUE TITLE
Generator package resolution

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/specs#131]
Currently generators are dependencies of the Prisma CLI. 

#### Problems

- Generates must be Node toolchain
- Users lose degree of control over Prisma2 version in use, say codebase needs older version of generator but they also want newer features of Prisma2, and vice-versa 
- Confusing: pluggable part of the architecture yet centrally distributed
- Generator development/examples are hurt in certain ways, [ref](https://github.com/prisma/nexus-prisma/issues/395)

#### Proposal

— edit, obsolete, scroll down

1. ~as is: generators are declared in prisma.schema~
2. ~`prisma generate`, for each generate declared, looks for a correspondingly-named cli on PATH~
3. ~if none found, then error~
4. ~if found, CLI is executed in accordance with well defined generator contract~

#### Tradeoffs: Gains

- Super flexible: Generator can be written in any language

#### Tradeoffs: Loses

- Forcing generator authors to craft a runnable CLI adds some complexity than if they they just had to write a lib for direct import
- Good Error handling and reporting for end-users may be more difficult to achieve, e.g. an imported lib can be used with language facilities (e.g. `try-catch`) and is part of the same system process as the CLI itself, whereas a system call to invoke another binary reduces such control and a bug in the generator CLI may run off with system resources, or whatever in ways that are much harder for the Prisma CLI to protect the end-user from.

#### Related

- [nexus-prisma side of this issue](https://github.com/prisma/nexus-prisma/issues/395)

**Comment by jasonkuhrt** [comment]
We could punt CLI-based to a future feature, starting with the existing system of TypeScript/JavaScript generator packages.

Then, we would just need to come up with a resolution system that, once package is found, dynamically imports it.

**Comment by jasonkuhrt** [comment]
Given the debrief presented today by @sorenbs and @schickling about a present focus on JS, I am doubtful that binary-on-path is the optimal ROI for us right now.

I sketched how a prisma-node-generators system might work.

Note how we can [easily] improve the DX with intelligent recovery thanks to a toolchain assumption that aligns with our foreseeable future (modulo Go).

#### Node-Generators Proposal

![image](https://user-images.githubusercontent.com/284476/64559691-e10c5800-d314-11e9-95e6-29194e3f0593.png)

**Comment by jasonkuhrt** [comment]
CC @Weakky @timsuchanek ... who else?

**Comment by jasonkuhrt** [comment]
I revised the proposal to account for a detect phase which makes explicit how we can do node in a non-mutually-exclusive way.

![image](https://user-images.githubusercontent.com/284476/64567204-af4fbd00-d325-11e9-90da-56a409d1b458.png)

**Comment by janpio** [comment]
> Am I bypassing a proper spec procedure? Sorry 🙈 Please point me in the right direction/process doc 🙏.

This is currently created. Right now it is pretty much a wild west, some buy-in from stakeholders and how this fits into the bigger picture would be nice though.

**Comment by jasonkuhrt** [comment]
Resolved in meeting September 16 with @divyenduz @timsuchanek @schickling @jasonkuhrt @Weakky. Only bin generators. Rely on Prisma Node SDK for good DX.
