### ISSUE TITLE
Issues with our current Schema

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#164]
After letting our Schema stew 🍜 a bit during preview and talking a bit with
@sorenbs and @schickling , we want to re-open some discussion points:

### Example

```groovy
model User {
  id        Int           @id
  customer  Customer?
  name      String
}

model Customer {
  id       Int     @id
  user     User?
  address  String
}
```

### What's in the spec

For 1:1 relationships, it doesn't matter which side you store the foreign key.
Therefore Prisma has a convention that the foreign key is added to the model who
appears first alphanumerically. In the example above, that's the `Customer`
model.

Under the hood, the models looks like this:

| **users** |         |
| --------- | ------- |
| id        | integer |
| name      | text    |

| **customers** |         |
| ------------- | ------- |
| id            | integer |
| user          | integer |
| address       | text    |

You **may** omit either `User.customer` or `Customer.user` and the relationship
will remain intact. This makes either the back-relation or the forward-relation
optional. If one side of the relation is missing, Prisma implies the field name
based on the name of the model it is pointing to.

https://github.com/prisma/specs/tree/master/schema#one-to-one-11-relationships

### Problem

This leads to a problem when you rename the model where that rename happens to
swap the order, you unexpectedly migrate the underlying relationship from
`Customer.user` to `User.Customer`.

#### 1. Disallow 2-sided one-to-one relationships:

```groovy
model User {
  id        Int           @id
  customer  Customer?
  name      String
}

model Customer {
  id       Int     @id
  address  String
}
```

**Downside** No aliases

|    **Name**     |   **-1 / 0 / +1**   |                                               **Why?**                                               |
| :-------------: | :------: | :--------------------------------------------------------------------------------------------------: |
|    @sorenbs     | **TODO** |                                                                                                      |
|   @schickling   | -1 | I think you should use embeds for this                                                                                                     |
|    @mavilein    | -1 | I can't query the user for a given customer anymore. |
| @matthewmueller |   0   | I'm okay with this, our alias can default to the name of the model which is you want 99% of the time |

#### 2. Add attribute to specify where the relation is stored

```groovy
model User {
  id        Int           @id
  customer  Customer?
  name      String
}

model Customer {
  id       Int     @id
  user     User? @key
  address  String
}
```

**Downside** verbose

|    **Name**     |   **-1 / 0 / +1**   |                                         **Why?**                                         |
| :-------------: | :------: | :--------------------------------------------------------------------------------------: |
|    @sorenbs     | **TODO** |                                                                                          |
|   @schickling   | +1 | Feels messy. This ties into application schemas vs. database schemas discussion                                                                                          |
|    @mavilein    | 0 | Painful but maybe ok. I would not use `@key` though. We should stick with `@references` and `@map`                                                                                         |
| @matthewmueller |   0   | I'm okay with this if we concede that writing schema files will mostly be done in studio |

#### 3. Add attribute to specify where the relation is stored

```groovy
model User {
  id        Int           @id
  customer  Customer?
  name      String
}

model Customer {
  id       Int     @id
  user     User(id)?
  address  String
}
```

Or `User->id` or `User[id]` or `User.id`.

**Downside** Mixes type information with field names

|    **Name**     |   **-1 / 0 / +1**   |                                            **Why?**                                             |
| :-------------: | :------: | :---------------------------------------------------------------------------------------------: |
|    @sorenbs     | **TODO** |                                                                                                 |
|   @schickling   | -1 | Needs more information to make a final call.                                                                                                |
|    @mavilein    | +1 | We had this on the table before. A syntax like `user User(id)` would feel very close to SQL. It does not solve the multi referrences issue though! |
| @matthewmueller |    +1    | User.id neatly resolves other issues like [Multi-Reference Relationships](https://git.io/Jesx1). **Update** It doesn't neatly solve Multi-Reference Relationships. |

## II. Arity of Implicit relations are unexpected

Based on: https://github.com/prisma/prisma2/issues/477#issuecomment-530302881

### Example

```groovy
model Task {
  id        String   @default(cuid()) @id @unique
  account Account
}

model Account {
  id        String   @default(cuid()) @id @unique
}
```

### Problem

It's unclear whether **Task** and **Account** have a one-to-one relationship or
a one-to-many relationship.

### What's in the Spec

You **may** omit either `User.customer` or `Customer.user` and the relationship
will remain intact. This makes either the back-relation or the forward-relation
optional.

https://github.com/prisma/specs/tree/master/schema#one-to-one-11-relationships

#### 1. Change Unspecified relations from one-to-one's to one-to-many's

If the back relation field is **unspecified** and the specified field is:

- a list: infer the back relation field as singular field.
- singular: infer the back relation as a list. So in both cases we would make
  sure that if only one side is specified the resulting relation would always be
  one to many.

|    **Name**     |   **-1 / 0 / +1**   |                       **Why?**                       |
| :-------------: | :------: | :--------------------------------------------------: |
|    @sorenbs     | **TODO** |                                                      |
|   @schickling   | +1 | Fine with this                                                     |
|    @mavilein    | +1 | Improvement over current spec. I think nobody will run into issues anymore. |
| @matthewmueller |    +1    | I think this is an improvement over the current spec |

#### 2. Remove unspecified relations

Disallow the schema above, require them to specify the back-relation. VSCode can
autocomplete it.

```groovy
model Task {
  id        String   @default(cuid()) @id @unique
  account   Account
}

model Account {
  id        String   @default(cuid()) @id @unique
  tasks     Task[]
}
```

|    **Name**     |   **-1 / 0 / +1**   |                                          **Why?**                                          |
| :-------------: | :------: | :----------------------------------------------------------------------------------------: |
|    @sorenbs     | **TODO** |                                                                                            |
|   @schickling   | 0 | Prefer the first over this solution                                                                                           |
|    @mavilein    | -1 | I tried this approach myself and it is extremely painful. We should not assume VS Code as a given. |
| @matthewmueller |    +1    | I prefer the explicitness + less magic. Tooling would allow you not to write this yourself |

**Comment by janpio** [comment]
(Best split these up into multiple issues already to make discussion possible)

**Comment by schickling** [comment]
Superseded by #223 and #224 based on votes above.
