### ISSUE TITLE
Prisma Schema SDK

### ISSUE THREAD

**Issue by Weakky** [prisma/specs#166]
[Rendered view](https://github.com/prisma/specs/tree/spec/prisma-schema-sdk/sdk-js/schema)

**Comment by MichalLytek** [comment]
I don't like the idea of enforcing a coding pattern in SDK. It should be as simple as fuck, not a clone of Nexus style of decorators style.

`graphql-js` is a great example of that - low level set of tools that allows to build a custom, opinionated solutions like nexus, with decorators or functional programming patterns.
