### ISSUE TITLE
Spec needed: multi field id API for Photon

### ISSUE THREAD

**Issue by mavilein** [prisma/specs#171]
We started the [epic](https://github.com/prisma/prisma-engine/issues/29)  for multi field id in the engines now. We discovered that we need  to spec how the GraphQL API and the corresponding DMMF representation  looks like. We can't spec this out yet because we don't know yet how the  API part in Photon will look like. This will probably have an influence  on how we should design the query engine API.

**Comment by mavilein** [comment]
I created this issue because i wonder if combined ids get a special treatment in the Photon API e.g. in`create` or `connect`.

**Comment by matthewmueller** [comment]
This one is specced out here: https://github.com/prisma/specs/pull/179

Let me know if you have any questions/concerns about the implementation. We're waiting on @schickling  to look it over.
