### ISSUE TITLE
Schema: Specify implemented vs. not implemented parts

### ISSUE THREAD

**Issue by janpio** [prisma/specs#172]
The schema spec currently does not specify exactly what is implemented and what is not:
https://github.com/prisma/specs/tree/master/schema

---

Add this below the headlines of stuff that is not implemented:

```
> ⚠ This is not implemented yet.
```

As per https://github.com/prisma/specs/blob/master/process/specs.md#implemented-vs-not-implemented

**Comment by mavilein** [comment]
I provided my input to this topic in this [PR](https://github.com/prisma/specs/pull/193).

**Comment by janpio** [comment]
Thanks @mavilein!

Any additional input on that or does the Schema spec now mark all the not implemented parts as "not implemented" correctly?

@matthewmueller @sorenbs @divyenduz @timsuchanek @schickling @mavilein @nikolasburk

**Comment by divyenduz** [comment]
Current state + Marcus's PR LGTM 👍

**Comment by schickling** [comment]
I cannot provide much feedback on what's implemented vs what's not, so please move forward on this.
Just be aware that the maturity level of current schema "spec" is still very early and will see quite a lot of changes in the coming weeks.

**Comment by sorenbs** [comment]
This spec is massive, but I am not aware of any remaining unmarked unimplemented features. LGTM 👍

**Comment by janpio** [comment]
Ok, we will treat the implementation status of the schema spec as "correct" from now on.
