### ISSUE TITLE
Rework action / TOC / tooling setup

### ISSUE THREAD

**Issue by janpio** [prisma/specs#180]
https://prisma-company.slack.com/archives/CFM8D5VHC/p1569576561017700?thread_ts=1569487751.014600&cid=CFM8D5VHC

```
Matt Mueller:balloon:  3 minutes ago
okay, i want to rework our actions anyway. i have merge conflicts every day with this new setup. changes:
1) prevent direct commits to master (UI changes have a button to commit to a branch, 3 more clicks with this setup)
2) run actions on commits to master
3) ask spec writers to run 1 command to setup a precommit hook, so they get nice TOC during PRs (edited) 


Jan:win:  1 minute ago
I mentioned it before:
Replace 3) with an adapted Github action that can manually generated TOCs on branches/PRs (precommit hook does not fire when using Github UI)

Jan:win:  < 1 minute ago
And 1 and 2 would probably be mutually exclusive (unless actions get an exception from the protected branch) (edited) 
```

**Comment by matthewmueller** [comment]
> 3) with an adapted Github action that can manually generated TOCs on branches/PRs (precommit hook does not fire when using Github UI)

Is this easy to setup? I'd be down for this but it would be in addition to precommit hooks. Precommit hooks give us a lot more flexibility in what we can do with them and you only need to set it up once.

Personally, I'd be willing to give this one up for now. Editing in the UI is mostly for small fixes that won't require large changes to the TOC.

**Comment by janpio** [comment]
> Is this easy to setup? I'd be down for this but it would be in addition to precommit hooks. Precommit hooks give us a lot more flexibility in what we can do with them and you only need to set it up once.

Should be, the action could probably be forked and the "react to all commits" part be replaced with "react to commits to master or comments with `/toc`" for example. That is what they tell you makes Github actions so awesome (but who knows, not tried it yet).

(We have a `/rebase` GitHub action installed that we can probably steal part of this from)

> Personally, I'd be willing to give this one up for now. Editing in the UI is mostly for small fixes that won't require large changes to the TOC. Once these changes get committed to master, the TOC will be updated.

I am not really - I spent multiple hours per day doing stuff in the web UI across many different specs.

In general I expect this kind of additive work (so not creating a new spec and spending a month on it until it is ready, but spending a few hours to edit an existing spec) to get more frequent in the future and the workflow should not be worse for that.


> > And 1 and 2 would probably be mutually exclusive (unless actions get an exception from the protected branch)
> 
> Ahh yep, actions run on master (protected branch). This proposal is very similar to how you'd setup CI for code.

Ok, that would enable switching the `TOC` action over to the suggested functionality. Sounds good.
