### ISSUE TITLE
Prettier / Formatter configuration

### ISSUE THREAD

**Issue by janpio** [prisma/specs#181]
Some people editing things here in this repo seem to use `prettier`. As there is no agreement on the exact configuration yet, this leads to PRs changing random formatting stuff. Talking about this over and over again is wasteful, so let's add a prettier (or whatever) configuration that can inform the local runs of these tools and can (probably) also be used by a GitHub action for the people editing via GitHub UI.

**Comment by schickling** [comment]
## VSC

```json
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
  "prettier.semi": false,
```

## `package.json`

```
"prettier": {
    "semi": false,
    "trailingComma": "all",
    "singleQuote": true
  }
```

**Comment by janpio** [comment]
Running `prettier` via Github action seems simple enough: https://stefanzweifel.io/posts/run-prettier-or-php-cs-fixer-with-github-actions/

**Comment by janpio** [comment]
I think @matthewmueller had mentioned that the default output of the TOC action conflicts with prettier somehow in that it removes the duplicate empty line. 

We have to find a solution for that (whatever it may be - we are not sold on the TOC action [which was merged a bit prematurely...] - and going back to the previous TOC tool and placeholder if it is run via a Github action would be totally valid solution here.)
