### ISSUE TITLE
Prisma Framework

### ISSUE THREAD

**Issue by janpio** [prisma/specs#182]
## Content

What is it?
What problems does it solve?
Which ideas are the base of it?
How did we end up here?
What use cases are covered?
...

## Motivation

Starting point of specs
Link to individual tools
Use cases other specs can build on
Ideas/Problems/Principles other specs can refer to
...

**Comment by janpio** [comment]
Many ideas for this in https://github.com/prisma/specs/pull/154 (Which tackled it from a technical POV)

**Comment by matthewmueller** [comment]
Note: unassigning myself on things I'm not actively working on. I may pick this up in the future.
