### ISSUE TITLE
Binary workflows (build, generation, download, ...)

### ISSUE THREAD

**Issue by schickling** [prisma/specs#2]
- Query Engine for Photon
  - Configured via `generator { platform = "..." }`
- CLI (for introspection + migrations)
  - Installed via `npm`, `curl`, `brew`, ...
- Prisma SDK

**Comment by matthewmueller** [comment]
Workflows have been specced out & issues to test various platforms have been created: https://github.com/prisma/specs/tree/master/binary-workflows

There's an open question about how high-level or specific do we want our compile targets, but I think we have time to chew on it for a bit before making any commitments: 

https://github.com/prisma/specs/tree/master/binary-workflows#production-installation
