### ISSUE TITLE
Binaries: Include Introspection Engine

### ISSUE THREAD

**Issue by janpio** [prisma/specs#208]
The Introspection Engine is currently becoming a thing and will replace the TS introspection code. Before that happened, the Introspection engine should also be included in the Binaries spec in appropriate ways.

**Comment by janpio** [comment]
Was added for Downloads etc, still missing for at least:
https://github.com/prisma/specs/tree/master/binaries#binaries-1
https://github.com/prisma/specs/tree/master/binaries#binary-protocols
https://github.com/prisma/specs/tree/master/binaries#environment-variables
https://github.com/prisma/specs/tree/master/binaries#configuration ("Environment variable to configure ..."

**Comment by janpio** [comment]
Note this will also affect the prisma2/docs content in several places, so when this is done a follow up issue for docs/niko should be created in prisma2.

**Comment by do4gr** [comment]
https://github.com/prisma/specs/pull/338
Some details I'll try to clear up with Tim
