### ISSUE TITLE
Explicit relation keys: Add attribute to specify where the relation is stored

### ISSUE THREAD

**Issue by schickling** [prisma/specs#224]
Supersedes #164

### Example

```groovy
model User {
  id        Int           @id
  customer  Customer?
  name      String
}

model Customer {
  id       Int     @id
  user     User?
  address  String
}
```

### What's in the spec

For 1:1 relationships, it doesn't matter which side you store the foreign key.
Therefore Prisma has a convention that the foreign key is added to the model who
appears first alphanumerically. In the example above, that's the `Customer`
model.

Under the hood, the models looks like this:

| **users** |         |
| --------- | ------- |
| id        | integer |
| name      | text    |

| **customers** |         |
| ------------- | ------- |
| id            | integer |
| user          | integer |
| address       | text    |

You **may** omit either `User.customer` or `Customer.user` and the relationship
will remain intact. This makes either the back-relation or the forward-relation
optional. If one side of the relation is missing, Prisma implies the field name
based on the name of the model it is pointing to.

https://github.com/prisma/specs/tree/master/schema#one-to-one-11-relationships

### Problem

This leads to a problem when you rename the model where that rename happens to
swap the order, you unexpectedly migrate the underlying relationship from
`Customer.user` to `User.Customer`.

### Solution

Add attribute to specify where the relation is stored

```groovy
model User {
  id        Int           @id
  customer  Customer?
  name      String
}

model Customer {
  id       Int     @id
  user     User? @relation(key: true)
  address  String
}
```

**Downside** verbose

**Comment by janpio** [comment]
> this was implicitly solved with the new relation syntax because now you must specify the side of the foreign key anyways
