### ISSUE TITLE
Parallel query execution / dataloader support

### ISSUE THREAD

**Issue by schickling** [prisma/specs#242]
TBD

**Comment by divyenduz** [comment]
Next steps: Tim, Marcus discuss how this might look like

**Comment by mavilein** [comment]
@timsuchanek, @dpetrick  and I had a meeting about this topic and here is a summary of our thoughts. @dpetrick will take some more time to dive into the details to find potential issues with this solution.

## Motivation
One of the main usecases of Photon is to use it inside a GraphQL server. The resolver system of a GraphQL server is prone to suffer from the N+1 problem. To mitigate this problem users can choose to implement the DataLoader pattern within the application server. This burdens our users with unnecessary work that is not related to their core domain. This issue explores how we could include a DataLoader implementation within Photon.

## Idea
To support the dataloader pattern easily in all Photon clients we will:
1. Extend the protocol to allow clients to send a batch of queries.
2. This batch of queries is optimised by the query engine only if certain rules apply.

### Protocol changes
We will extend our protocol to allow the sending of batches. The request payload will look like this:
```json
{
    "batch": [
        {"query": "{ findOneUser({id: 1}) {id, name} }"},
        {"query": "{ findOneUser({id: 2}) {id, name} }"},
        {"query": "{ findOneUser({id: 3}) {id, name} }"}
    ]
}
```

### Optimization Rules in the Query Engine

The query engine will not optimize any arbitrary combination of queries that are sent as a batch. A batch of queries will only be optimized if all of the following rules apply to this batch:
* All queries are of type `findOne` for the same model type.
* All queries use the same unique field of the model as the criteria for the where argument.
* All queries use the same selection set.

These rules simplify implementation a lot but still serve the main usecase.

**Comment by jasonkuhrt** [comment]
I don't see deduping mentioned here but as I understand it its one of the important features of dataloader. Maybe it is implied by this thread but wanted to double check.

If 1000 comments are fetched, including the author of each comment, every time an author is encountered that has already been/is already being fetched then it [photon] would defer to the dataloader cache.

For this to work, the selection set needs to be part of the key calculation. For example if post author is selected and includes a subset of the fields that comment authors are selected for, then we must not dedupe in this case. The general solution off the top of my head is resource IDs + selection sets = dataloader keys.

**Comment by timsuchanek** [comment]
Someone of product needs to confirm that this is the right approach.
We will first tackle the batching and in a separate step the deduping.

**Comment by timsuchanek** [comment]
Deduping is being tracked https://github.com/prisma/specs/issues/306

**Comment by janpio** [comment]
Internal Note: Create issues is appropriate locations for Backend and TS.
