### ISSUE TITLE
CLI specs are broken

### ISSUE THREAD

**Issue by janpio** [prisma/specs#252]
https://prisma-specs.netlify.com/cli/init/blank-project/
![image](https://user-images.githubusercontent.com/183673/66773535-7fb14900-eebf-11e9-969a-f4567791c501.png)

And all the others as well.

**Comment by janpio** [comment]
Seems to work on an iPhone - but not in the normal browser.

**Comment by pantharshit00** [comment]
I would try to fix it this weekend if no one else picks this up(Hacktoberfest 🎃 )

**Comment by janpio** [comment]
Oh yes please do. 

I did a thing myself to try to get rid of https://github.com/prisma/specs/issues/251 at https://github.com/prisma/specs/pull/258, but that solved one problem and then showed the next one ;) (Those are probably interconnected, and both should really be fixed.)

**Comment by janpio** [comment]
Moved to https://github.com/prisma/spec-cli
