### ISSUE TITLE
Spec needed: implicit back relation fields

### ISSUE THREAD

**Issue by mavilein** [prisma/specs#253]
The PSL spec currently does not outline the logic around implicit back relation fields.

Became obvious when implementing [this](https://github.com/prisma/prisma-engine/issues/102), which should now probably be the behavior contained in the spec.

**Comment by matthewmueller** [comment]
Based on discussion with @mavilein

1. It does not mention the rule for the arity of the back relation field.

```groovy
?
```

2. It should also describe how the name is determined, e.g. a singular field is called post and list field would be posts.

```groovy
model User {
  posts Post[]
}

model Post {
  // implied: user User
}

// or

model User {
  // implied: posts Post[]
}

model Post {
  author User
}
```

3. This rule can only work if the generated name is not conflicting with existing field. 

```groovy
model User {
  posts Post[]
}

model Post {
  // implied: user User
  user Other // error(!)
}

// or

model User {
  // implied: posts Post[]
  posts Other // error(!)
}

model Post {
  author User
}
```

**Comment by matthewmueller** [comment]
closed via: https://github.com/prisma/specs/commit/11460c62c33181a083ad395566822935c7d04925
