### ISSUE TITLE
Tool to upgrade Prisma 1.x Schema to new schema format

### ISSUE THREAD

**Issue by janpio** [prisma/specs#260]
Old title: `prisma convert`

This is a feature, it needs to be described.

Update: Current CLI description:

```
λ prisma2 convert -h

Convert a datamodel 1.1 to datamodel 2

Usage

  prisma2 convert

Options

  -h, --help       Displays this help message

Examples

  $ cat old-datamodel.prisma | prisma2 convert > new-datamodel.prisma
```

**Comment by schickling** [comment]
This command should be hidden and not officially be part of the CLI. It should rather be removed from the CLI instead of added as a spec.

**Comment by janpio** [comment]
No support for converting Prisma 1.x schemas to Prisma Framework?
Or do you just want to hide it and treat it as a voluntary thing?

**Comment by schickling** [comment]
My suggestion: This should live somewhere in the docs as part of an upgrade guide (e.g. as an interactive web app).

**Comment by janpio** [comment]
Ok, so we do not do it as part of the CLI but as something additional (which could of course also be another CLI if this makes the most sense.)
