### ISSUE TITLE
Is Prisma Schema modeled after GraphQL or SQL?

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#266]
One of the most interesting topics that fell out of yesterday's conversation was learning @nikolasburk's perspective on the Prisma Schema.

It'd be useful to clarify our design goals here. Modeling in GraphQL is very different from modeling in SQL. **Right now we make decisions that go both ways.** 

So far I think we've approached the Prisma Schema as an abstraction over SQL. This has led to decisions like this:

```groovy
model User {
  id Int @id
  firstName String 
}

model Post {
  id Int @id
  user User
}
```

If you're coming from an [SQL perspective](https://github.com/prisma/prisma2/issues/477) your mental model would look like this:

```sql
create table User (
  id int primary key
  firstName text
);

create table Post (
  id int primary key
  user int not null references User (id)
);
```

In this world, **users have many posts**.

However, if you come from a GraphQL perspective:

```graphql
type User {
  id: Int! @id
  firstName: String!
}

type Post {
  id: Int! @id
  user: User!
}
```

It's a bit hard for me to "unsee" SQL, but I'd imagine you'd expect a one-to-one relationship here.

---

cc/ @schickling @nikolasburk @mavilein

**Comment by jasonkuhrt** [comment]
> but I'd imagine you'd expect a one-to-one relationship here.

Why? 

IIUC that GraphQL inspired schema you've shown states that a `Post` node can have an edge to a `User` node.
