### ISSUE TITLE
Implicit to explicit form using `prisma format`

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#267]
Given the following Prisma Schema:

```groovy
model User {
  id Int @id
}

model Post {
  id Int @id
  user User
}
```

If you look at this schema on it's own, you probably wouldn't assume that a **User has many Posts**.

The example above is the implicit form. Here's the explicit form:

```groovy
model User {
  id Int @id
  posts Post[]
}

model Post {
  id Int @id
  user User
}
```

In this example, we name the back-relation explicitly (e.g. posts Posts). I believe this makes the relationship User has many Posts obvious.

Being explicit would also save us a lot of headache across our tooling and simplify the syntax for the user:

- Less possible weird states the user can fall into
- Less thinking around types of relations & back-relations 
- May lead to less code, where the implicit relationships only need to be handled in the formatter.

We also don't want to go fully **explicit** because it's painful to always type out the back-relations. 

**Possible Solution**

Use `prisma format` to automatically fill in the other side of the relation. When you see this filled in, you'll have the opportunity to edit this. If you don't run format during your workflow, you'll see an error when you run `prisma lift save`, `prisma lift up`.

![format](https://user-images.githubusercontent.com/170299/67105739-9f02eb80-f1c9-11e9-814f-aab298bb6b83.gif)

## Related issues

- This also neatly resolves issues like #262
- Also solves #278
- Also solves #226
- Supersedes #259
- Also solves #213 via https://github.com/prisma/prisma-engine/issues/87

**Comment by divyenduz** [comment]
This may work if we make prisma format more mainstream :heart:
1. support across editors
2. tutorials as best practice to run your schema through it

**Comment by janpio** [comment]
Is there any reason why someone might want or have to be implicit about the relations? (Besides lazyness, or that the DB system does not have the concept to express it [or doesn't care about it])

If you don't run format during your workflow, you'll see an error when you run prisma lift save, prisma lift up.
Does this suggestion only work if this is a requirement? Or would it also benefit from being an optional thing that people can do (e.g. if they are already using our formatter)?

**Comment by mavilein** [comment]
This looks really neat to me. What do you mean with those 2 points?

> * Introspection engine doesn't need to encode these rules
> * Migration engine doesn't need to encode these rules

Because right now they don't encode rules around that topic imo. The rules for back relation fields are centralized in the datamodel parser. Upon parsing we run a component called `Standardiser` that adds those fields. This component would likely also be used by the introspection at some point.

**Comment by mavilein** [comment]
There's one caveat though. We will have cases where adding the back relation field is not possible because there would be a name conflict. E.g.:
```
model User {
  id Int @id
  posts Int // oh oh there is already a back relation field
}

model Post {
  id Int @id
  user User
}
```

**Comment by matthewmueller** [comment]
@divyenduz 

Agreed on both points. I think we'd want to do this regardless of this proposal.

---

@janpio 

> Is there any reason why someone might want or have to be implicit about the relations? (Besides lazyness, or that the DB system does not have the concept to express it [or doesn't care about it])

That's a good point. I don't see any downsides of having an extra API method from photon's perspective, but I also don't care if we add something to hide it. If we agree on the general approach, we can discuss what the default auto-filling should look like. 

@schickling mentioned:

```groovy
model User {
  id Int @id
  _ Post[]
}

model Post {
  id Int @id
  user User
}
```

or 

```groovy
model User {
  id Int @id
  post Post[] @hide
}

model Post {
  id Int @id
  user User
}
```

This would mean that it's there, but doesn't show up in Photon. @mavilein noted adding `_` adds complexity to engineering.

> Does this suggestion only work if this is a requirement? Or would it also benefit from being an optional thing that people can do (e.g. if they are already using our formatter)?

We could also say that it's optional, it just adds complexity to engineering. I'd prefer that engineering just needs to maintain and test the explicit flows but I don't have strong feelings about this one way or another and would defer to @mavilein to make this call.

---

@mavilein 

> Because right now they don't encode rules around that topic imo. The rules for back relation fields are centralized in the datamodel parser. Upon parsing we run a component called Standardiser that adds those fields.

Cool that makes sense. I've updated the original comment to the reality more clear.

> There's one caveat though. We will have cases where adding the back relation field is not possible because there would be a name conflict. E.g.:

My understanding from @do4gr is that this is already an error. 

I think we can work around this in the formatter by either naming the auto-filled in one `posts1` or even just `posts`, you see the error and you rename manually.

**Comment by schickling** [comment]
I definitely like this idea @matthewmueller. This could also be well combined with `prisma dev` running in the background in case someone is not using an editor integration.

**Comment by mavilein** [comment]
I guess this issue is a foundation to describe a possible solution. Afterwards it will be turned into a specification. The spec must describe the logic for the following cases:
* A user does not add the back relation field. What's the error that the parser should display in this case?
* What's the expected behavior if the back relation field can not be added because a field with that name already exists? I am especially curious about the behavior within `prisma dev`.
* Are there any special rules for self relations?

**Comment by matthewmueller** [comment]
Specing this will be my focus next week.

**Comment by matthewmueller** [comment]
Didn't have time for this one. I'll probably pick it back up in a couple weeks. First steps are to decide on how much magic PSL will bring.

**Comment by matthewmueller** [comment]
Note: unassigning myself on thing I'm not actively working on. I may pick this up in the future.

**Comment by mavilein** [comment]
I am working on this right now. Work is tracked in this [issue](https://github.com/prisma/specs/issues/348).

**Comment by janpio** [comment]
Replaced by #348
