### ISSUE TITLE
`prisma dev` Studio improvements

### ISSUE THREAD

**Issue by schickling** [prisma/specs#27]
@nikolasburk 
- [ ] Rename to `Studio web endpoint`
- [ ] Remove `admin` URL suffix

@kuldar 
- [ ] Add loading state for Studio

**Comment by janpio** [comment]
This should probably be split into a studio issue (loading state) and a CLI issue (where `prisma dev` lives).

**Comment by janpio** [comment]
> * [ ]  Rename to `Studio web endpoint`

If this is still wanted it should just be an issue in `prisma2`.




> * [ ]  Remove `admin` URL suffix

Could not find that.



> * [ ]  Add loading state for Studio

Think that already exists.

Closing.
