### ISSUE TITLE
Postgres Polymorphism 

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#274]
**Use Case**

Imagine you're building Facebook's news feed. The news feed can have photos, posts and videos.  How do you store this data? 

```groovy
model Photo {
  id Int @id
}

model Text {
  id Int @id
}

model Video {
  id Int @id
}

type Post = Photo | Text | Video
```

**Option 1: Super table**

```sql
create table Post (
  id bigserial primary key 
);

create table Photo (
  id bigserial primary key references Post (id) on delete cascade on update cascade,
  photo_url text not null
);

create table Text (
  id bigserial primary key references Post (id) on delete cascade on update cascade,
  text text not null
);

create table Video (
  id bigserial primary key references Post (id) on delete cascade on update cascade,
  video_url text not null
);
```

**Option 2: Shared Sequence**

```sql
create sequence post_id;

create table Photo (
  id bigint primary key default nextval('post_id'),
  photo_url text not null
);

create table Text (
  id bigint primary key default nextval('post_id'),
  text text not null
);

create table Video (
  id bigint primary key default nextval('post_id'),
  video_url text not null
);
```

**Comment by stephenh** [comment]
FWIW I was going to file a new issue asking about this; i.e. if I have traditional polymorphic behavior ("a photo feed item, a post feed item, etc"), it'd be great to get that in/out of prisma2 with ideally polymorphic-aware typing.

I.e. traditional ORMs would do with this `class PhotoFeedItem extends FeedItem` and then either table-per-class or single-table-for-all-sub-classes modeling.

It'd be great if prisma could do something like ADTs, i.e. a `type FeedItem = PhotoFeedItem | PostFeedItem` with `type PhotoFeedItem { kind: "photo, ..."`.

Granted, the database schema's/prisma schema's metadata model is going to have to cooperate on somehow providing what those kinds are.

Is that in scope for this ticket? Or prisma2 in general? Happy to file another ticket if this is something different.

**Comment by schickling** [comment]
Thanks a lot for your comment @stephenh, that's exactly what we're aiming for. In regards to the "issue structure": Polymorphic relations will probably be a "Prisma concept" which will be mapped to the Postgres feature, so opening a new issue for that would probably be best. This issue rather tracks the Postgres-specific design.
