### ISSUE TITLE
Reconcile enums behavior

### ISSUE THREAD

**Issue by schickling** [prisma/specs#277]
This issue is a continuation of https://github.com/prisma/prisma2/issues/741 to track the needed spec changes. For convenience here's @mavilein's comment:

> This is a temporary workaround that we still need. It exists for two reasons:
> 1. This allows to easily add required columns although data exists already. Right now we don't have a spec yet how the CLI should behave in that case. We would need to present some kind of error to the user.
> 2. SQLite is a special thing again. SQLite errors when adding a required column even though the table is still empty. We would nee to implement a workaround for this quirk for SQLite by first creating a column as nullable and then updating it to non nullable.

**Comment by matthewmueller** [comment]
For my understanding, this issue is about the following:

1. We want to change the Enum syntax.
2. We should take into account the restrictions @mavilein brought up

**Comment by matthewmueller** [comment]
Taking myself off this since I have no idea what this is about. Feel free to reassign me once there's clarification.
