### ISSUE TITLE
Implicit self relations

### ISSUE THREAD

**Issue by schickling** [prisma/specs#278]
![image](https://user-images.githubusercontent.com/1567498/67682989-cd828280-f990-11e9-805a-d45d4cfe6d66.png)

**Comment by mavilein** [comment]
This is not an issue anymore i think. This was about the foreign key column getting changed due to our hidden defaults. But with our current syntax you would write the initial schema as this:
```
model Human {
  id      Int    @id
  son     Human? @relation(fields: [humanId], references: [id])
  humanId Int?
}
```
Then the father would get added and the foreign key column would stay untouched.
