### ISSUE TITLE
CLI: Update Notifier

### ISSUE THREAD

**Issue by janpio** [prisma/specs#281]
Users should be notified of available updates of the CLI.

**Comment by idan** [comment]
@janpio done

**Comment by matthewmueller** [comment]
todo: Create a spec for update notifier

**Comment by janpio** [comment]
@idan transferring issue looses their labels, we have to be careful to apply those again after the move or information will be lost. (No idea why GitHub can/does not apply the same ones again if they exist...)

**Comment by janpio** [comment]
There is now a CLI stub at https://github.com/prisma/specs/tree/master/cli. You can probably add the "Update Notifier" under https://github.com/prisma/specs/tree/master/cli#other-functionality
