### ISSUE TITLE
Define @default with Enums

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#296]
Discussion: https://prisma-company.slack.com/archives/CEYCG2MCN/p1572864125261000

**Comment by matthewmueller** [comment]
- `color Color @default("RED")`
- `color Color @default(Red)`
- `color Color @default(Color.Red)`

**Comment by janpio** [comment]
Internal Note: This should probably be a bug - find out.

**Comment by mavilein** [comment]
I tried locally and the following example worked for me:

```
model User {
  id     String     @default(cuid()) @id @unique
  email  String     @unique
  name   String?
  status UserStatus @default(CONFIRMED)
}

enum UserStatus {
  CONFIRMED
  UNCONFIRMED
}
```

**Comment by mavilein** [comment]
Closing this as it works as expected. Let's reopen if that is actually not the case.
