### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by schickling** [prisma/specs#3]
# Update

## Missing

- [ ] Consolidate @nikolasburk's additions
- [ ] Create spec for known errors (e.g. assign error code)
- [ ] Validate spec fulfills requirements of
  - [ ] https://github.com/prisma/prisma/issues/3392#issuecomment-514999567
  - [ ] https://github.com/prisma/specs/issues/42

---

## Areas

- Photon error handling
- CLI (lift) error handling
- Error codes across tools

## Error codes

Let's create a spec that lists out all possible errors with a concrete code (probably incremental).
Error codes will span across the entire platform of tools (incl. PhotonJS, CLI, query engine, ...) and have to be "globally unique". Probably the best way to do this is by having some kind of pre-fixing scheme (e.g. `err-lift-1532`). (We should do more research on best practices for error code naming / formatting etc.)

### Example usage with Photon

```ts
function myCode() {
  try {
    await photon.users.create()
  } catch (e) {
    switch (e.code) {
      case 230: 
    }
  }
}
```

## Dependencies 

- List of known query engine errors
- List of known migration engine errors

# Notes

- Credentials masking (see https://github.com/prisma/prisma2/issues/112)

**Comment by matthewmueller** [comment]
Specced: https://github.com/prisma/specs/blob/errors/errors/Readme.md

**Comment by heymartinadams** [comment]
Now here, fyi: https://github.com/prisma/specs/tree/master/errors
