### ISSUE TITLE
Introspection - Open Questions from Sample Schema Collection

### ISSUE THREAD

**Issue by do4gr** [prisma/specs#304]
I introspected the majority of the schemata collected here https://github.com/prisma/database-schema-examples.

This is a collection of patterns that are not covered yet by PSL and that need to be discussed and possibly specced: 

* How do we handle relations without foreign key constraints? Can a user just define them in PSL? We need to check whether the query engine relies on them. Also the migration engine would then need to know not to create them? (MySQL: all MyISAM based schemata e.g. wordpress, InnoDB: prestashop)
* Some tables had no primary key defined. SQLite, MySQL and Postgres all allow this. Prisma relies on having one field defined as the id to use. There were two patterns for this: 
    * An auto incrementing serial column that just wasn't defined as primary (but still called id) Here the user could just add the @id, but the migration engine would probably need to know not to set the primary key. 
    * Compound unique composed of a scalar column and a foreign key column. The query engine could not handle this at the moment since our distinction between scalar and relationfields is pretty strict. (MySQL: kanboard)
* There were also cases of the primary key being a column with a foreign key constraint. These represented inheritance on the db level. The query engine could not handle this at the moment.  (Postgres: sportsdb)
* How do we handle collation? This can be specified on a column level in the db. 
* How do we handle timezones for date times? At the moment our logic for reading and writing times does not check the db settings. This will result in the outputted dates / times being wrong. 
* Some columns did not use the datatype one would expect: For example char(1) or tinyint ←> boolean, or integer <-> timestamp. The user probably handled that discrepancy either in their SQL statements or in their application code. Do we need custom mappings like {'t' ←> true; 'f' ←> false;  }? (MySql: drupal, lychee, prestashop )
* Currently our way of specifying indexes does not allow for the definition of an index length on text columns. This is necessary and using the max value by default might be wasteful. (MySQL: mediawiki, drupal)
* Currently Enums are introspected as Strings. Should Prisma make use of db level Enums where possible? We have not done this so far, but handled this in the core. But this means that during introspecting a Prisma db, we can't tell String and Enum apart. (MySQL: Piwigo, test_db; Postgres: standup-slack-bot)

**Comment by janpio** [comment]
> * How do we handle collation? This can be specified on a column level in the db.

Open issue at https://github.com/prisma/specs/issues/73

**Comment by mavilein** [comment]
That only applies to MySQL, right?

> Currently our way of specifying indexes does not allow for the definition of an index length on text columns. This is necessary and using the max value by default might be wasteful.

**Comment by do4gr** [comment]
Looks like  SQLite and Postgres don't care. Apparently SQLServer also has some limitations, maybe others as well.
