### ISSUE TITLE
 How should lift show errors for unexecutable migrations?

### ISSUE THREAD

**Issue by mavilein** [prisma/specs#308]
Currently we don't have error handling in place for migrations that are not executable. We did not have the time to finish this before Prisma Day.

We need a spec that describes how lift should display errors for migrations that are not executable. The spec should think about how we could give users hints on what they should do. (I wonder wether we should tackle this before we have hooks in place.)

List of migrations that are not executable:
1. Adding a required field for a model that already has records. -> Currently we always set a default value for columns although the corresponding field does not have `@default` set. This makes this kind of migration executable. This behavior is obviously weird and results in questions like [this](https://github.com/prisma/lift/issues/197).
1. Updating an optional field to required for a model that already has records with null values for that field. -> Currently not handled at all.
1. Adding a unique constraint to a model but there are already records that violate this constraint. -> Currently not handled at all.
1. Deleting an enum value that is already in use in some record. -> Currently not handled at all.

I compiled this list of errors based on this piece of code from [Prisma 1](https://github.com/prisma/prisma/blob/alpha/server/servers/deploy/src/main/scala/com/prisma/deploy/validation/DestructiveChanges.scala).

**Comment by tomhoule** [comment]
From the discussion with @mavilein and @janpio on slack:

In these scenarios, we have ask the user to fix their schema. My first idea would be a very detailed error message that points the user to the exact place in their datamodel where they need to make the change, and suggests ways to make the migration they want based on the specific problem.

One question we need the spec to answer is whether the diagnostics are purely schema based or if lift should try to look at the data (e.g. to see if the new unique constraint would work, for example).

But as Marcus noted in the issue, hooks will probably influence the solution to this problem.

**Comment by janpio** [comment]
![image](https://user-images.githubusercontent.com/183673/68483058-1bbe3e00-023b-11ea-9d55-be44c4188d15.png)

**Comment by tomhoule** [comment]
We do display these errors currently, and the CLI handles them differently (no prompt to apply the migration anyway, since we know it wouldn't work). This is taken into account in the current migrations work as well. This issue can be closed.
