### ISSUE TITLE
Introspection - Renaming of Fields and Types

### ISSUE THREAD

**Issue by do4gr** [prisma/specs#309]
The current Typescript implementation does extensive renaming. 
* uppercasing and singularizing model names
* camelcasing column names
* changing relation field names (e.g. user_id -> user)

The current Rust implementation does none of this. What is our desired behavior there?

**Comment by mavilein** [comment]
As of now we don't want any of this automagic behavior. Our consideration was that we will introduce this at a later point again. It might become configurable by the user at that point.
