### ISSUE TITLE
Introspection - Backrelation Fields

### ISSUE THREAD

**Issue by do4gr** [prisma/specs#311]
The current Typescript implementation does not autogenerate back relation fields for more complex cases instead leaving comments for the user to disambiguate the fields manually. 
Rust currently uses heuristics to generate unambiguous, but potentially very long and ugly, names. 

What is the behavior we want there?

<img width="806" alt="Screen Shot 2019-11-11 at 14 04 01" src="https://user-images.githubusercontent.com/16278407/68589425-21f72900-048c-11ea-8d28-dc63e0a8bd58.png">

**Comment by mavilein** [comment]
We will go with long ugly names in the beginning. We have a proposal to force that back relation fields must always be present. For user convenience they would be automatically added through `prisma format`. So we will have to implement this behavior anyway and will need to tweak it over time anyway.
