### ISSUE TITLE
Introspection - Enums

### ISSUE THREAD

**Issue by do4gr** [prisma/specs#312]
Currently the Typescript implementation recognizes db level enums. In Postgres they are named and shared between columns, in MySQL they are defined per column. 

So if one introspects a MySQL db, one can end up with something like this: 
<img width="392" alt="Screen Shot 2019-11-11 at 14 51 34" src="https://user-images.githubusercontent.com/16278407/68592202-c67c6980-0492-11ea-838d-608ffec31937.png">

There is lots of repetition for the Enums since a unique one is created in the schema for each Model+field even if they are using the same values. Is this the desired behaviour? This would need to be implemented for the Rust introspection. 

Additionally, we do not persist or change Enum values on the db level using Lift. So changing the available Enum values in the PSL would result in the Query Engine allowing for the new values and then a failure on the db level since Lift does not adjust the permitted values there. 

What is the behavior we want there? Should we push Enums changes to the db level if possible? 
Should we persist Enum constraints on the db level when starting with PSL and lift? (Otherwise introspecting a Project started with Prisma will turn Enum fields into String fields without constraints.)

**Comment by mavilein** [comment]
Whatever behavior we have right now is fine. Enums are unspecced as of now and we don't know yet which direction we will go.
