### ISSUE TITLE
Introspection - Default Values

### ISSUE THREAD

**Issue by do4gr** [prisma/specs#313]
Currently the Typescript implementation does not parse db level default values but the Rust version does.

* What is our desired behavior for default values and Lift? 
* Should we change default values on the db level if the user changes them in PSL? 
* Should Prisma projects store the default values also on the db level? Otherwise this information is lost when introspecting.

**Comment by mavilein** [comment]
Default values should be propagated by lift to the underlying database. If this is not the case this is a bug in the `migration-engine`.
