### ISSUE TITLE
Native Scalar Lists

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#321]
**Prior Art**: @mavilein defined a concept of native lists for Datamodel 1.1 with `scalarList`: https://github.com/prisma/prisma/issues/3403

---

Currently scalar lists in a Prisma Schema are represented as a has-many relationship with two tables.

For example:

```groovy
model Post {
  id String @id @default(cuid())
  tags String[]
}
```

Results in the following SQL for Postgres:

```sql
create table Post (
    id text primary key
);

create table Post_tags (
  nodeId text references Post (id) on delete cascade,
  position integer,
  value text not null,
  primary key (nodeId, position)
)
```

Though a bit magical, the purpose of this multi-table approach is to find a single way to support lists across all types and datasources. 

There is a more idiomatic way to do this in databases that support native lists:

**Postgres**

Postgres has a concept of list types:

```sql
create table Post (
    id text primary key,
    tags text[] not null
);
```

**MySQL**

MySQL doesn't have list types, but does have a JSON type:

```sql
create table Post (
    id text primary key,
    tags json not null
);
```

This wouldn't be as strict (you could insert objects, numbers, strings), but if we disallow this at either the query engine level or in photon we should be okay.

---

**Proposal**

I propose we support lists like `String[]`, `Float[]`, whenever we can represent these lists safely and efficiently in the database. 

In databases that do not support it, it's a compiler error and the user must use relations instead:

```groovy
model Post {
  id string @id @default(cuid())
  tags Tag[]
}

model Tag {
  tag string @id
  position Int
  post Post
}
```

And we document how to **mimic** lists using relations.

---

**Open Questions**

- How much engineering effort would it be to transition over to native scalar lists?

**Comment by mavilein** [comment]
@matthewmueller : Can you be a bit more specific in the proposal and explain what is the definition of `we can represent these lists safely and efficiently in the database`? Right now i can't tell if you consider a json column safe enough or not. If you do consider it safe enough i wonder whether string columns wouldn't be safe enough either. Then almost every database would support them imo.
Please also outline the implications for introspection associated with the proposal. Our original goal was to have a isomorphic introspection. This proposal would not accomplish this in all cases imo.

**Comment by matthewmueller** [comment]
Thanks @mavilein for pointing out the areas where I need to expand.

> we can represent these lists safely and efficiently in the database

What I mean by **safely** is that it's a distinct type that we can introspect and see that it's a list type. So maybe MySQL **shouldn't** have `String[]`, it should just support `JSON`. 

What I mean by **efficiently** is that it provides us methods to search within the arrays:

- Postgres: `select * from posts where tags in ('soccer', 'sports')`
- MySQL: something like: `SELECT JSON_SEARCH('["1","2","3","4","5"]', 'one', "2") is not null 
`

> Please also outline the implications for introspection associated with the proposal.

I think the **distinct type** requirement would cover the introspection case fully, but let me know if you see a case I'm missing.

**Comment by mavilein** [comment]
> I think the distinct type requirement above would cover the introspection case fully, but let me know if you see a case I'm missing.

Yes i agree. This would only be interesting it we used shims/polyfills.

I agree with this approach. The result is that we will allow native scalar lists only for Postgres right now. In MySQL and SQLite users will have to use one of the aforementioned workarounds. Less magic is good. We can still later add convenience features to make this less painful if needed. 👍

**Comment by schickling** [comment]
Looks great to me. While we don't have embeds yet fully specced out nor implemented, I suggest to spec out the workaround using embeds instead of models.

**Comment by idan** [comment]
🎉 Excellent. Looks like we have consensus. Product's input here is complete.

Following discussion with eng leadership, next step here is for engineering to document things in their preferred fashion. @mavilein @janpio let us know if product can be helpful in doing that.

**Comment by janpio** [comment]
This happened via https://github.com/prisma/specs/pull/326, which is now the basis for implementation work.
