### ISSUE TITLE
@@index in schema spec

### ISSUE THREAD

**Issue by divyenduz** [prisma/specs#341]
We have the `@@index` syntax floating around but that is not mentioned in the [schema spec](https://github.com/prisma/specs/tree/master/schema). This issue tracks covering that. 

This syntax can be used to convey to lift that we need backing indexes for a field or a compound index for a group of fields. 

Related issue: https://github.com/prisma/specs/issues/280

**Comment by janpio** [comment]
Internal Note: 
https://prisma-company.slack.com/archives/CEYCG2MCN/p1576233434352900?thread_ts=1576142648.319600&cid=CEYCG2MCN
This seems to be implemented in the Query Engine at least already.

Introspection Engine also creates it (in some cases possibly only).

**Comment by mavilein** [comment]
Documented in this [commit](https://github.com/prisma/specs/commit/d1bb5111cf48575e640139b6d9c7cbf0d54133c2).
