### ISSUE TITLE
Compound foreign keys

### ISSUE THREAD

**Issue by mavilein** [prisma/specs#345]
Assume the following SQL schema (Postgres) :

```sql
CREATE TABLE user (
  id TEXT,
  first_name TEXT,
  last_name TEXT,
  PRIMARY KE(id)
);

CREATE TABLE Post (
  id TEXT,
  author_first_name TEXT,
  author_last_name TEXT,
  FOREIGN KEY (author_first_name, author_last_name) REFERENCES user(first_name, last_name),
  PRIMARY KE(id)
);
```

**Currently there's no possibility to express this SQL schema in an equivalent PSL schema.** PSL is currently lacking the ability to define a relation field that is backend by a compound foreign key. The relation field needs to specify two informations:
1. what are the names of the referenced fields / columns?
1. what are the names of the underlying columns of that field?

The first information is specifyable through `@relation(references: [firstName, lastName])`. But the second information is not specifyable as of now. I suggest to reuse the `@map` directive for this case. Hence the corresponding PSL would look like this:

```groovy
model User {
  id String @id
  firstName String @map("first_name")
  lastName  String @map("last_name")
}
model Post {
  id String @id
  author User @relation(references: [firstName, lastName]) @map(["author_first_name", "author_last_name"])
}
```

**Important Details**
* The directive `@relation(references: [firstName, lastName])` referes to the field names in the model `User`.  But the directive `@map(["author_first_name", "author_last_name"])` refers to the underlying column names for those fields.
* The order of the field names in `@relation` has to correspond to the order of column names in `@map`.

**Comment by do4gr** [comment]
LGTM

**Comment by sorenbs** [comment]
### Decision

This is what we will do. I will create a spec PR.

**Comment by mavilein** [comment]
This is implemented.
