### ISSUE TITLE
Make implicit relation rules explicit through prisma-fmt

### ISSUE THREAD

**Issue by mavilein** [prisma/specs#348]
## Current State
Consider the following SQL schema example:
```sql
CREATE TABLE user (
  id TEXT,
  PRIMARY KE(id)
);

CREATE TABLE Post (
  id TEXT,
  author TEXT,
  FOREIGN KEY (author) REFERENCES user(id),
  PRIMARY KE(id)
);
```

Photon allows to traverse the relation from both sides:
```ts
// traverse from Post to User
const user = await photon.posts.findOne({ where: { id: "the-truth-about-superman" }}).author();
// traverse from User to Post
const posts = await photon.users.findOne({ where: { id: "clark-kent" }}).posts();
```

This necessitates that both sides of the relation are specified in the PSL schema:
```groovy
model User {
  id String @id
  posts Post[]
}
model Post {
  id String @id
  author User
}
```

This brings up the question on which side the foreign key is stored? Currently we have the following rules in place so that the user does not need to specify it themselves:

**Rule 1: Many to Many Relations**
If a relation is many to many we use an implicit intermediate join table. This rule only works on SQL databases. Document and NewSQL databases don't need join tables and therefore should not use this rule. We would probably need to fall back to rule 3 for those.

Example PSL:
```groovy
model Post {
  id String @id
  tags Tag[] 
}
model Tag {
  id String @id
  posts Post[]
}
```

**Rule 2: One to Many Relation**
If a relation is one to many we store the foreign key on the many side. E.g.: A user has many posts. The foreign key is stored in the post table pointing to the user table.

Example PSL:
```groovy
model User {
  id String @id
  posts Post[] 
}
model Post {
  id String @id
  author User
}
```

**Rule 3: One to One Relation**
If a relation is one to one there's no straightforward rule. Hence we decided to use lexicographical ordering. We store the foreign key on the model with the lower lexicographical order. If it is a self relation we use the field names for comparison instead. E.g.: A user has one login. One login is assigned to only user. The foreign key is stored within the login table because it has the lower lexicograpical value.

Example PSL:
```groovy
model User {
  id String @id
  login Login
}
model Login {
  id String @id
  user User
}
```

### 1. Side of foreign key must be specified explicitly
The implicit rule is removed. In all cases the side of the foreign key must be specified explicitly. The example for the 1:1 relation would look like this then:

```groovy
model User {
    id String @id
    login Login @relation(references: [id])
}
model Login {
    id String @id
    user User
}
```

### 2. Make the syntax more concise
The removal of the implicit rules means that a lot more characters are added to the schema. We could introduce a more concise syntax that is akin to the syntax of SQL foreign keys. `Login @relation(references: [id])` gets replaced by `Login(id)`.

```groovy
model User {
    id String @id
    login Login(id)
}
model Login {
    id String @id
    user User
}
```

### 3. Implicit Rule exists but is turned into explicit form on reformat
The implicit rule provided convenience as the location of the foreign key is clear in cases like 1:n and m:n. It would be annoying for the user to type this out if we can know where the foreign key must be stored. Hence we could still allow the old syntax but on reformat through `prisma-fmt` the explicit syntax is added. This way people get educated about the placement of foreign keys by seeing it after saving in vs code.

**Comment by matthewmueller** [comment]
Thanks for writing this up. Strongly in favor of the suggested changes, but I'd really like to see us remove implicit many-to-manys for SQL relations. 

The reasons being:

- We need to help the user (with dialog) to move from the implicit to explicit, rather than it just being declarative.
- We need naming rules, hidden tables, rules to handle name conflicts, etc.

I'd be very happy to have `prisma-fmt` do the reformatting from implicit many-to-many to explicit many-to-many.

**Comment by schickling** [comment]
All above sounds great to me but I would like to not introduce additional syntax like `Login(id)` - at least for now as we don't yet have a firm grip of all the schema semantics and concepts.

**Comment by mavilein** [comment]
@matthewmueller : I'm fairly sure that we need the implicit many-to-manys. If we would do this change now the consequences would be:
1. Every user code dealing with many to many relations would stop working. Users would have to adapt their code which would become a whole lot uglier.
2. Even if they do those changes it would still not work as the query engine can not handle this at the moment. There's no way we can make that happen in the short term.

And btw the introspection already does not return the implicit form anyway. So there's no problem here.

**Comment by sorenbs** [comment]
Thanks Matt!

That is certainly a valid argument regarding implicit many-many relations, but not for the reason you have described. As I wrote in [339](https://github.com/prisma/specs/issues/339#issuecomment-559534963), I think implicit many-many is a solved problem: Introspection and Lift should both simply follow our convention when printing and reading the schema.

---

The main reason I am interested in including the implicit many-many syntax is that they enable a simpler Photon API for the majority that does not need extra fields on the relation table.

### Traversing implicit many-many relation:

```
model User {
  posts Post[]
}

model Post {
  user User[]
  title String
}
```

```
prisma.users.findOne(...).posts()[o].title
```

### Traversing explicit many-many relation:

```
model User {
  posts UserPost[]
}

model UserPost {
  user User
  post Post
}

model Post {
  user UserPost[]
  title String
}
```

Our current implementation support these queries:

```
prisma.users.findOne(..., include: {posts: {post: true}}).posts()[0].post.title
prisma.users.findOne(...).posts({ include: { post: true } })[0].post.title
```

In the future we could extend our automatic `map` application in photon in order to enable this query:

```
prisma.users.findOne(...).posts().post()[0].title
```

So, the call to make is wether the gain from simpler Photon API is worth the extra complexity in the Schema (having both implicit and explicit many-many is more complex than just having the explicit version).

**Comment by matthewmueller** [comment]
@mavilein @sorenbs thanks for taking the time to write this. Maybe it's just a matter of time horizon then. 

FWIW, I'm not putting up roadblocks for MVPhoton. You could convince me of just about any amount of scope cut. What I'm trying to avoid is making life overly difficult for us as we go for MVLift. Removing code to make our future lives easier seems like not a big hill to climb to me.

AFAIK, The reasons I describe are in direct response to the answers provided in #339.

> Introspection should follow our conventions when printing schema

Our conventions have led or will lead to *naming rules, hidden tables, rules to handle name conflicts, etc.*. 

This isn't that big of a deal, I just see this as extra fluff code we need to test, maintain, & think about. Assuming we're aligned on using UI to primarily interact with the schema, why do we need to be so concise?

A edge case question. Say I handwrite the following:

```groovy
model Post {
  id Int @id
  tags Tag[]
}

// Unrelated (coincidental) model
model _PostTag {
  id String @id
  name String
}

model Tag {
   id Int @id
   posts Post[] 
}
```

And then run `lift up`, what is our strategy?

This is a bit contrived, but I envision a handful of corner cases we'll need to deal with for a win in syntax conciseness. Are we already covered for these cases?

> VS Code plugin should support converting from implicit to explicit, making it easy to add a field to the relation table

This feels like a very easy pit to fall into. I see the benefit of offering the little VSCode lightbulb to fix this, but I don't think this should be the only way to edit the schema.

This is analogous to VSCode offering to generate code to satisfy an interface. Sometimes you take it, sometimes you want to just write it out by hand. I'd prefer we don't make the *write out by hand* workflow almost impossible to get right.

---

The way we (Idan & I) thought about Photon was that it would add support for implicitly passing through the join table. Using your example above:

```groovy
model Post {
  userPosts UserPost[]
}

model UserPost {
  user User
  post Post
  isCreator boolean
  canEdit boolean
}

model Post {
  userPosts UserPost[]
  title String
}
```

```js
// query the join table
const userPosts = await user.find(10).userposts()
console.log(userPosts[0].canEdit)

// query through the join
const posts = await user.find(10).posts()
console.log(posts[0].title)
```

Maybe the heart of the difference of opinion is the idea that join tables with extra columns is an uncommon workflow. I don't think this is true at all. I believe most apps will need them within the first couple days of modeling your data.

**Comment by sorenbs** [comment]
Thanks @matthewmueller! Many great considerations. Unfortunately we won't be able to act on any of them for the initial Photon release. We will revisit this again later.

**Comment by sorenbs** [comment]
We have reached a decision on this issue:

- We will implement proposal 1) and 3) from the initial issue.
- We will not implement proposal 2) as @schickling has unspecified concerns. We will revisit this as a potential improvement after the initial Photon release.

@mavilein and @janpio - we can begin implementation.

**Comment by mavilein** [comment]
Open Question: Do we want to expose `prisma-fmt` through a CLI command. Otherwise non vs code users can't use it.

**Comment by sorenbs** [comment]
> Open Question: Do we want to expose `prisma-fmt` through a CLI command. Otherwise non vs code users can't use it.

Yes, we should add a `prisma fmt` command to the CLI.

**Comment by sorenbs** [comment]
> We have reached a decision on this issue:
> 
> * We will implement proposal 1) and 3) from the initial issue.

@mavilein - now that I think about it, we will actually just implement proposal 3. Is that right?

**Comment by mavilein** [comment]
> @mavilein - now that I think about it, we will actually just implement proposal 3. Is that right?
@sorenbs - Yes. This is is also my thinking.

**Comment by mavilein** [comment]
implemented in https://github.com/prisma/prisma-engines/commit/5b1e76acdd8d2c8680695756d54cfd4369f59967
