### ISSUE TITLE
Make prisma-engine source of truth for actual error messages

### ISSUE THREAD

**Issue by janpio** [prisma/specs#371]
https://github.com/prisma/prisma-engine/tree/master/libs/user-facing-errors/src + https://prisma-company.slack.com/archives/CFM8D5VHC/p1575887166004200

Error spec will afterwards only be about how errors work in general, the actual error descriptions will not be part of the file any more.

**Comment by divyenduz** [comment]
Interesting, is this decision made? I can imaging users of the SDK might have to read rust code to understand errors and implement on top of it.

Also, does the error spec now link to this file or remove the tables. What is the exact change that is required?

**Comment by janpio** [comment]
Yes, this decision is made to remove the requirement to have duplicated list of errors. SDK users are currently not the main target group of this document, the Rust developers are. It will be trivial to generate a "source of truth" table from the Rust code when we are at this stage.

How exactly the spec is being changed is up to the people working on this of course, but in general I would expect it to link to these files or that folder, which then maybe has a README that explains what is where and why - but maybe that part is also in the errors spec itself.

**Comment by divyenduz** [comment]
> It will be trivial to generate a "source of truth" table from the Rust code when we are at this stage.

I was also thinking along the same lines, not too important right now. 

Overall, I agree

**Comment by mavilein** [comment]
[PR](https://github.com/prisma/specs/pull/378) for the spec is ready. Awaiting review.
