### ISSUE TITLE
Photon.js error formatting

### ISSUE THREAD

**Issue by timsuchanek** [prisma/specs#377]
# Problem
The default behavior of Photon.js is, to print pretty errors with colors, stack trace and if available, helpful tips to get out of the situation. In order to add colors to error messages, it utilizes ANSI escape characters. This is an example of how it gets rendered in a terminal:

![image](https://user-images.githubusercontent.com/1094804/71890168-ff0f8b00-3143-11ea-84b3-94fa118fec85.png)

While this has been designed to be printed in the terminal, which handles ANSI escape characters, not all environments can do so. Especially if you are only interested in the machine-readable error message, this formatting of the error gets cumbersome to consume.

An example of that is `graphql-js`, which returns the error message in the response payload to a query like so:

![image](https://user-images.githubusercontent.com/10392539/71469621-bcc18200-2804-11ea-9431-66685f7dff79.png)

# Solution

In order to tackle this problem, we need to distinguish the different error formatting levels we want. These are the three proposed levels:

1. **Pretty Error**: Includes a full stack trace with colors, syntax highlighting of the code and extended error message with a possible solution for the problem. (*default*)
2. **Colorless Error**: Same as pretty errors, just without colors.
3. **Minimal Error**: Just the pure error message.

### Pretty Error
![image](https://user-images.githubusercontent.com/1094804/71890679-231f9c00-3145-11ea-934d-5329118b32fa.png)

### Colorless Error
![image](https://user-images.githubusercontent.com/1094804/71890734-43e7f180-3145-11ea-8834-219ee0a2c856.png)

### Minimal Error
![image](https://user-images.githubusercontent.com/1094804/71890771-52cea400-3145-11ea-9acb-49f8eb967e71.png)

### How to configure this?
In order to configure these different error formatting levels, we have two options: Environment variables and the `Photon` constructor.

#### Environment variables
1. `NO_COLOR`: If this env var is provided, colors are stripped from the error message. Therefore we end up with a **colorless error**. The `NO_COLOR` environment variable is a standard described [here](https://no-color.org/). We have a tracking issue [here](https://github.com/prisma/prisma2/issues/686).
2. `NODE_ENV=production`: If the env var `NODE_ENV` is set to `production`, only the **minimal error** will be printed. This allows for easier digestion of logs in production environments.

#### Constructor args
The constructor argument to control the error formatting is called `errorFormat`. It can have the following values:
- `undefined`: If it's not defined, the default is `pretty`
- `pretty`: Enables pretty error formatting
- `colorless`: Enables colorless error formatting
- `minimal`: Enables minimal error formatting

It can be used like so:
```ts
const photon = new Photon({
  errorFormat: 'minimal'
})
```
As the `errorFormat` property is optional, you still can just instantiate Photon like this:

```ts
const photon = new Photon()
```

#### Error codes
Important note: If there is an error code available as defined [here](https://github.com/prisma/specs/tree/master/errors#error-codes), it will be added as a `code` property to the error object. This is the case for all error levels.

**Comment by matthewmueller** [comment]
Thanks for writing this up. I'm absolutely +1 on supporting `NO_COLOR`,  `isatty` etc.

I'm a bit torn on building in different types of error formatters. I think I'd rather see us define a `Reporter` interface with a `report(error: Error): Promise<void>` that you can pass in and is capable of formatting errors however the user sees fit. I guess we could bundle some default error reporters in. I kind of think we should just pick the right one for the user as a default.

I'd also like us to consider how this fits in with log levels and logging in general. Presumably we'll have different log levels (error, warning, info, debug, trace, etc.). This error formatter lives as additional configuration within the error log level or perhaps on top of the error level. 

We'll also want to be able to pass in custom loggers that are able to ship logs off to remote log ingestion systems. Could this perhaps be one interface?

**Comment by timsuchanek** [comment]
Thanks for your feedback @matthewmueller!

I think there are two major goals we have here: 1. Human readability and 2. Machine readability.

### 1. Human readability
With the three different error formatting levels, we ensure that the errors are human-readable.

### 2. Machine readability
This issue is just about the error message. Error codes will independent of this discussion always be present if available, therefore errors can be handled programmatically.


Exposing a reporter interface would require us to give users a lot of parameters, not just an `Error` as an argument to the reporter function, as it would require everything that could potentially go into the error message.

As we have different errors from validation, query engine query errors and panics, the array of different informations needed for the reporter is quite big.
As an example just validation errors. There are a few different kinds of validation errors, all of them have different metadata:

- ArgError
- AtLeastOneError
- AtMostOneError
- FieldError
- InvalidArgError
- InvalidFieldError

Exposing this level of abstraction would mean exposing implementation detail. If we e.g. want to change the kind or shape of validation errors, it's possible without a breaking change, as long as error codes stay the same. If we bake their metadata and form into a reporter interface, it would mean a breaking change each time we slightly change the errors.
In other words: With the error formatting levels and error codes, we keep the surface minimal.

Regarding logging: This ties in nicely into logging levels. We have 3 different logging levels: `query`, `info` and `warn`. It soon will be in the Photon spec, until then here a quick overview:

## Logging & Debugging

### Logging

All engine related logs can be configured with the `log` property.
These are examples how to specify different log levels:

Just providing the log levels, stdout as default

```ts
const photon = new Photon({
  log: ['info', 'query'],
})
```

Changing on a per log level, where the logs end up: As an event or in stdout.

```ts
const photon = new Photon({
  log: [
    {
      level: 'info',
      emit: 'stdout',
    },
    {
      level: 'query',
      emit: 'event',
    },
    'WARN',
  ],
})

photon.on('query', e => {
  console.log(e.timestamp, e.query, e.args)
})
```

Log level names get mapped to the event name for the event emitter.

```ts
const photon = new Photon({
  log: [
    {
      level: 'info',
      emit: 'event',
    },
    {
      level: 'query',
      emit: 'event',
    },
    {
      level: 'warn',
      emit: 'event',
    },
  ],
})

photon.on('query', e => {
  e.timestamp
  e.query
  e.args
  console.log(e)
})

photon.on('info', e => {
  e.timestamp
  e.message
  console.log(e)
})

photon.on('warn', e => {
  e.timestamp
  e.message
  console.log(e)
})
```

**Comment by matthewmueller** [comment]
Thanks for the info about logging! That covers the use cases I had in mind nicely.

> Exposing a reporter interface would require us to give users a lot of parameters, not just an Error as an argument to the reporter function, as it would require everything that could potentially go into the error message.

Got it. So it sounds like internally to Photon we have something like the following, segmented by some key like `type`.

```ts
type Err = ArgError | AtLeastOneError
type ArgError = { type: "ArgError", code: "101", arguments: ["id", "name"] }
type AtLeastOneError = { type: "AtLeastOneError", code: "102", missingArgument: ["id"] }
```

This allows us to switch over the types of errors and access the specific metadata for each error and format the error in a unique way for each case. That definitely sounds like too much for a user to deal with.

The way I was thinking about it was something like this:

```ts
type Err = { type: string, code: string, message: string, meta: { [key: string]: JSON }
interface Reporter {
  report(error: Err): Promise<void>
}
```

Where we can't really do anything custom, but would be generic and shouldn't break over time, unless your reporter is expecting certain keys to be present in `meta` (which it shouldn't be).

Anyway, I can see pros and cons to both approaches, let's go with your approach!

**Comment by jasonkuhrt** [comment]
> This allows us to switch over the types of errors and access the specific metadata for each error and format the error in a unique way for each case. That definitely sounds like too much for a user to deal with.

Maybe, but certainly not for a machine. For example `santa` might want to integrate these errors into its own rendering, doc, etc. system.

Also, at runtime, in production, if these errors make their way (as JSON) into the users' log system (e.g. ELK) then having the structured data might be useful to visualize, segment, whatever, on.

Aside:

Lastly will say, I don't personally buy the idea that users cannot handle strongly structured errors. These are not an afterthought, an aside. They are, I think, as core as the types coming off the successful path. This is one of the learnings that we can take from Rust, Haskell, etc. where `Either` types turn errors into first-class strongly-typed values that programs _have_ to handle. (Not sure what the `Go` philosophy here is).

Some elements of the GraphQL community at least are talking about this now too, e.g. https://blog.logrocket.com/handling-graphql-errors-like-a-champ-with-unions-and-interfaces/.

```gql
type User {
  id: ID!
  login: String!
}

type UserNotFoundError {
  message: String!
}

union UserResult = User | UserNotFoundError

type Query {
  user(id: ID!): UserResult!
}
```

> it would mean a breaking change each time we slightly change the errors.

Agree with @matthewmueller's point about at least using a simpler type that captures the envelope including `code`, but not the data (`meta` `context` whatever we call it). I

**Comment by timsuchanek** [comment]
Thanks for the responses!

@jasonkuhrt something which I didn't make clear in my previous comments:

There are mostly 3 kinds of errors: 1. **Validation errors** 2. **Query errors** 3. **Panics**

As a tool author, you are probably interested in handling all of them programmatically, whereas a user mostly needs to handle 2. and 3. programmatically. Validation errors can only occur if you don't follow the type definitions of Photon.

Therefore, if there are any validation errors, I can fix them during development of my app.

Errors related to queries and mutations that I'm sending (**Query Errors**), include all the structured data that's available.

Example of a unique constraint error:
![image](https://user-images.githubusercontent.com/1094804/71992297-73762700-3235-11ea-947b-9811b76aab08.png)

So today unique constraint errors include a `code` property and a `meta` property, that you can use programmatically and this won't be affected by this spec, as this spec is only about **error messages**. But if applicable, we add all the structured data that makes sense.

The additional metadata of validation errors I consider for now as an implementation detail that should not end up in the public Photon API, but if the use-case is there, we can think about exposing that information for library authors.

**Comment by janpio** [comment]
Was this persisted in some spec file?
