### ISSUE TITLE
[Idea] How opting into Polyfills could look like

### ISSUE THREAD

**Issue by mavilein** [prisma/specs#382]
This [idea](https://prisma-company.slack.com/archives/CFM8D5VHC/p1579096663000100) initially popped up in our company slack. Documenting it here for public purposes.

Recently we removed the support for scalar lists on MySQL and SQLite in the spirit of just exposing was the database has to offer. As expected some users are not happy about that choice. This change does not mean that this feature has to be gone forever. We could bring it back. But if we do we should require users to explicitly opt in into this polyfill. 

Here are two ideas of how this could look like:
```prisma
model Post {
  id String @id
  tags String[] @polyfill
}
```
or maybe with a global setting for the whole datasource:
```prisma
datasource db {
  provider = "sqlite"
  polyfils = [scalarLists]
}
```

**Comment by beeman** [comment]
Just my 2 cents on this matter, I definitely prefer version 2, defining these kind of things for the whole datasource at once.

I think that makes more sense because it would allow somebody to switch from Postgres to SQlite by only adjusting the provider. In the first example they would need to go through the whole schema and sprinkle changes around :)

**Comment by divideby0** [comment]
@schickling I saw you self-assigned this back in January, any updates as far as roadmap? For use case context, our production database is Postgres but we'd love to be able to run our tests in SQLite as it can be setup and torn down faster without an external service dependency. The one thing stopping us right now is that our production schema makes use of enums and JSON types, which aren't supported directly in the SQLite provider but would have some pretty straightforward polyfills to String values, at least as far as I can tell. This feature seems like it'd be a really nice complement to https://github.com/prisma/prisma/issues/1487.

**Comment by macrozone** [comment]
would be nice to have enums back in sqlite. It's handy for local development, but missing enums makes it nearly unusable.

**Comment by luxaritas** [comment]
Django does this with many of its ORM features, with enums coming to mind in particular. IIRC they actually have some level of database implementation too by using a CHECK constraint. I'm happy for "polyfills" to be opt in (knowing what the gotchas are/that there are gotchas is great), but I definitely support Django's approach of providing a uniform API with fallbacks especially when there are limited potential issues eg in performance (especially for SQLite which is typically going to be used for development and testing)
