### ISSUE TITLE
What should be the supported database string/url schemes for SQLite?

### ISSUE THREAD

**Issue by tomhoule** [prisma/specs#385]
The "canonical" scheme we used for SQLite database URLs in datasources is `file://`.

The current implementation doesn't agree on whether we support `sqlite://` in addition to `file://` and that causes unexpected behaviour. The two most likely options would be:

- Decide we support both `sqlite://` and `file://` URLs, and implement `sqlite://` support where it is missing.
- Decide we only support `file://`, and make the datamodel parser reject `sqlite://` URLs with a user-friendly error.

cc @divyenduz @janpio

**Comment by tomhoule** [comment]
![Screenshot from 2020-01-20 15-23-47](https://user-images.githubusercontent.com/13155277/72733741-c2f31600-3b98-11ea-99f9-7a4da6b032cf.png)

**Comment by Jolg42** [comment]
https://github.com/prisma/prisma/issues/2941#issuecomment-661388481
> As sqlite: seems to have worked in the past, we decided to keep this as an alias of file: which will be the official, documented way to reference SQLite databases.
