### ISSUE TITLE
Prisma Client JS: Exposing pgBouncer compatibility

### ISSUE THREAD

**Issue by timsuchanek** [prisma/specs#386]
The query engine allows configuring a new flag called `--always_force_transactions`, which enables compatilibity with pgBouncer.
https://github.com/prisma/prisma-engine/pull/403#issue-365425419

We need to spec out how this option is exposed in Prismas Client JS.

**Comment by matthewmueller** [comment]
Do you think it would make sense to offer an escape hatch for configuration like this? Something like:

```
extraFlags: [`--always_force_transactions`]
```

This would give us a chance to get features out here for folks without deliberating too much on APIs.

**Comment by timsuchanek** [comment]
Generally, that's a good idea, but we're leaking implementation detail here.
We might e.g. decide, that we instead use an env var.

Especially when introducing the Neon bindings in a couple of months from now, that interface will change. That would then be a breaking change for our users.

If we, however, have a specific argument in the constructor for this case, we can underneath replace it with whatever way of configuring the query engine we want.

Therefore, I would just introduce an arg like so:
```ts
new PrismaClient({
  alwaysForceTransactions: true
})
```
The `always` is kind of redundant here, because when you force something, you probably do that always in this context.
So going with 
```ts
new PrismaClient({
  forceTransactions: true
})
```
would also be an option.

**Comment by janpio** [comment]
This was temporarily implemented with the suggested name by @timsuchanek: https://github.com/prisma/prisma-client-js/issues/499 We will update to whatever is decided in this issue.
