### ISSUE TITLE
`prisma dev` Connection error

### ISSUE THREAD

**Issue by schickling** [prisma/specs#39]
Can occur if:
- DB not started
- Wrong DB credentials
- DB not reachable (e.g. port closed)

**Comment by janpio** [comment]
Can you please apply the correct `area` label @nikolasburk?

**Comment by schickling** [comment]
Next steps:
1. @divyenduz to spec out the underlying known errors
2. @nikolasburk to create CLI specs for the error handling / printing

**Comment by divyenduz** [comment]
This is done after the implementation of the errors spec, the following behaviors are observed: 

1. DB does not exist: Ask to create the DB
![image](https://user-images.githubusercontent.com/746482/70920508-018a3380-2023-11ea-9970-e79d207b2b3c.png)

2. DB not started: Notify user to confirm if the DB is running
![image](https://user-images.githubusercontent.com/746482/70920588-241c4c80-2023-11ea-821b-cdd1fa892cff.png)

3. Wrong credentials: Tell user that the credentials are not correct
![image](https://user-images.githubusercontent.com/746482/70920716-53cb5480-2023-11ea-92ac-a95aebba453f.png)

4. Port closed: same as not reachable/running
![image](https://user-images.githubusercontent.com/746482/70920894-97be5980-2023-11ea-9b4c-d1261c3dde90.png)
