### ISSUE TITLE
Prisma Client JS: Introduce clear differentiation between error types

### ISSUE THREAD

**Issue by timsuchanek** [prisma/specs#390]
You can distinguish Prisma Client errors into the following categories:

### TypeScript
1. Validation Error

### Rust
2. Panic
3. Known Error originating from Engine
4. Unknown Errors that did not lead to a panic.

We should make them clearly identifiable.

This can be added to the existing Prisma Client JS spec instead of the error spec, as this is about Prisma Client JS specific error handling.

**Comment by janpio** [comment]
That sounds super valuable.

**Comment by timsuchanek** [comment]
https://github.com/prisma/specs/pull/405

**Comment by timsuchanek** [comment]
Specced in #405 and implemented in the latest alpha.
