### ISSUE TITLE
CLI spec: some commands are missing

### ISSUE THREAD

**Issue by Jolg42** [prisma/specs#410]
I found that the CLI spec at https://github.com/prisma/specs/blob/master/cli/README.md

Is missing the following commands
- `validate`
- `studio`
- `lift save|up|down`

Note: these commands can take the --schema argument.

**Comment by Jolg42** [comment]
Dropping: Will need to be done after going through product first.

**Comment by sorenbs** [comment]
We do not want to spec stuff that hasn’t been thought out by product yet (studio and lift), and we don’t want to publicly document validate at this time.

**Comment by janpio** [comment]
Lift also does not exist any more... ;)
