### ISSUE TITLE
Clean labels in GitHub

### ISSUE THREAD

**Issue by Jolg42** [prisma/specs#430]
The labels to be renamed
- photon -> prisma-client
- photonjs -> prisma-client-js
- photongo -> prisma-client-go?
- lift -> migrate

<img width="248" alt="Screen Shot 2020-02-24 at 15 20 56" src="https://user-images.githubusercontent.com/1328733/75159882-5334f580-5719-11ea-9a31-e0fd394cd781.png">

**Comment by janpio** [comment]
For the `specs` repo this is a bit more involved:
1. Rename the labels manually
2. Adapt https://github.com/prisma/prisma-labelsync/blob/master/src/labels/repositories/specs.ts to the new label names
3. Hope nothing broke along the way

**Comment by janpio** [comment]
This is now done.
