### ISSUE TITLE
Introduce version field in Prisma Schema

### ISSUE THREAD

**Issue by schickling** [prisma/specs#437]
In order to better deal with (breaking) changes in the Prisma Schema Language (PSL) and to have a single source of truth for the used Prisma version in a project we need to introduce a `version` field to the Prisma schema.

> Further details are still WIP. ⚠️

**Comment by Weakky** [comment]
Akin to a lot technologies like [`docker-compose`](https://docs.docker.com/compose/compose-file/compose-versioning/), I like that idea and think it's critical to support breaking changes on the long term. Docker compose handles that pretty well with [a dedicated release notes page](https://docs.docker.com/compose/compose-file/compose-versioning/) for the updates of the docker-compose schema. They're also in a similar situation as we are: They have the docker-compose schema, and the "Docker Engine".

It might also become a nice forcing functions to keep retro-compatibility with older versions further down the down.

Being able to explicitly set the PSL version and the binaries versions could be useful both for end-users (avoid breaking changes) and library authors to explicitly pin the version when needed (eg: in tests)
