### ISSUE TITLE
Introspection

### ISSUE THREAD

**Issue by schickling** [prisma/specs#44]
## Discussion / Open Questions

- [ ] Abstraction spectrum: DB schema vs application schema
- [ ] "Knobs & Dials": Casing, abstraction level, ...
- [ ] Heuristics (e.g. missing foreign/primary keys, ...)

## Related

- [ ] Support for introspecting tables without an ID field https://github.com/prisma/prisma2/issues/175
- [ ] Introspection does not "auto" resolve ambiguous relations https://github.com/prisma/prisma2/issues/176

**Comment by janpio** [comment]
Related: "Here is a high level view of the state of the introspection engine that we are working towards." https://github.com/prisma/specs/issues/94

**Comment by janpio** [comment]
Things under "Related" in the issue are changes to an "existing" spec ("Introspection") (that is currently just a PR somewhere, but will exist properly one day).

**Comment by matthewmueller** [comment]
Note: unassigning myself on things I'm not actively working on. I may pick this up in the future.
