### ISSUE TITLE
Broken links in readme file 

### ISSUE THREAD

**Issue by jeffvandyke** [prisma/specs#477]
From deadlinkchecker.com:

Status | URL | Source link text
-- | -- | --
404 Not Found | https://github.com/prisma/specs/blob/master/prisma-client-go | Prisma Client Go
404 Not Found | https://github.com/prisma/specs/blob/master/migrate | Prisma Migrate
404 Not Found | https://github.com/prisma/specs/blob/master/sdk | SDK
404 Not Found | https://github.com/prisma/specs/blob/master/process/release-milestones.md | Release Milestones
404 Not Found | https://github.com/prisma/specs/blob/master/photon | Prisma Client

**Comment by janpio** [comment]
This has all been fixed - thanks for reporting.
