### ISSUE TITLE
Improve CLI Introspection ergonomics

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#50]
It took me about 5 tries to get this right:

```sh
prisma2 introspect --pg-db prisma-blog --pg-host localhost --pg-port 5432 --pg-schema public --pg-user m --pg-password ""
```

We can make this a lot better with sensible defaults:

```sh
prisma2 introspect postgres://localhost:5432/prisma-blog
```

**Comment by matthewmueller** [comment]
To spec this one out further. This is backed by `psql` and postico's default:

```
psql
```

```json5
{
  "protocol": "postgres",
  "host": "localhost",
  "port": 5432,
  "schema": "public",
  "sslmode": "disable",
  "user": "m", // your hostname
  "database": "m" // your hostname
  "password": "" // empty
}
```

```
psql prisma-blog
```

```json5
{
  "protocol": "postgres",
  "host": "localhost",
  "port": 5432,
  "schema": "public",
  "sslmode": "disable",
  "user": "m", // your hostname
  "database": "prisma-blog"
  "password": "" // empty
}
```

I think we can apply this model across databases.

**Comment by janpio** [comment]
Do you just want to add the database URI string as an argument to the command or does this include other changes to the existing flags?

**Comment by matthewmueller** [comment]
my proposal is to ditch the other flags and and standardize on connection strings

**Comment by matthewmueller** [comment]
Note: unassigning myself on things I'm not actively working on. I may pick this up in the future.

**Comment by janpio** [comment]
Introspection command has been reworked and uses the connection string now (or via schema.prisma file actually)
