### ISSUE TITLE
Improve introspection, then generate workflows

### ISSUE THREAD

**Issue by matthewmueller** [prisma/specs#51]
After introspecting, you can't directly generate. We should make this workflow better:

```sh
$ prisma2 introspect --pg-db prisma-blog --pg-host localhost --pg-port 5432 --pg-schema public --pg-user m --pg-password ""
✔ Introspecting database public: 108ms

Created datamodel definition based on 4 database tables
Created 1 new file: Prisma DML datamodel (derived from existing database)

  datamodel-1564666131.prisma
```

```sh
$ prisma2 generate
Error: Could not find /Users/m/Code/src/github.com/matthewmueller/prisma/capabilities/schema.prisma
```

Right now we require the following steps:

**1) rename `datamodel-1564666131.prisma` to `schema.prisma`**

**Suggestion**: We can eliminate this step entirely in the default case and just write out a `schema.prisma`

After I fix the `schema.prisma`, I'll run generate again:

```sh
$ prisma2 generate
info You dont have defined any generator in your schema.prisma, so nothing will be generated. You can define them like this:

generator photon {
  provider = "photonjs"
}
```

**Suggestion**: In this case, I'd suggest we write a generator either by default or have an interactive workflow to add a generator if there isn't one that will write to the schema.

**2) Copy and paste the `generator` block**

After I fix the `generator` block, I'll run generate again:

```sh
$ prisma2 generate
Generating Photon JS Client to $HOME/prisma/capabilities/node_modules/@generated/photon
```

**Suggestion**: Make the path relative to CWD, tell the user how to use this. Right now generating into @generated/photon is a new technique and we need to educate our users on how to use it.

**Comment by janpio** [comment]
Should be part of https://github.com/prisma/specs/pull/153

**Comment by divyenduz** [comment]
Internal note: We don't know what this is about

**Comment by matthewmueller** [comment]
### Proposed Next Steps

**1. Improve `prisma2 introspection` command**

```sh
$ prisma2 introspect postgres://localhost:5432/prisma-blog
```

- [ ] Cleanup flags, replace with `prisma2 introspect <url>`
- [ ] Write out to `prisma.schema` or if there are multiple schemas `prisma/prisma.schema` 
- [ ] *(optional)* remove *Created datamodel definition...* following the [Unix Rule of Silence](https://homepage.cs.uri.edu/~thenry/resources/unix_art/ch01s06.html)

**2. Run `prisma generate` command** 

```sh
$ prisma generate
```

- [ ] By default, lookup the prisma schema to `prisma.schema` or `prisma/prisma.schema` 
- [ ] *(optional)* remove *Generating Photon JS Client...*

**Comment by janpio** [comment]
We should probably split these suggestions into a Introspection and a Generate one.

**Comment by matthewmueller** [comment]
I don't care much, but the reason I put them together is to make sure that commands work well together.

**Comment by matthewmueller** [comment]
Just updated the proposal with what to do about re-introspection. It's very similar to the lift flow so I didn't feel the need to go further in-depth. If you find parts of it confusing let me know and I can sit down with you, then clarify.

Not entirely sure how else to push this forward. From my perspective it's ready to be implemented.

**Comment by timsuchanek** [comment]
@idan and @schickling will give feedback to move this forward.

**Comment by jgoux** [comment]
Hello,

Using prisma from a db-first perspective (meaning I don't want to touch prisma's own model, I do everything from my database with introspection), I agree that the current process is not optimal.

I would expect to have the datamodel-[timestamp].prisma file to have always the same name (so files don't sum up) and to be in photon's generated folder (currently there is a schema.prisma in it, but without any model, it's just a copy for my original schema.prisma defining my database source and my generator).
