### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by schickling** [prisma/specs#53]
- Should it be possible to use different Photon, Lift, ... versions at the same time? If so, how is it configured?

**Comment by schickling** [comment]
Update: Based on internal discussions about how to deal with breaking changes, this topic has become a lot more relevant and urgent.

My current suggestion would be to introduce a `version` field in the Prisma schema file.

**Comment by sorenbs** [comment]
This issue will be repurposed to describe our change infrastructure.
