### ISSUE TITLE
Create spec about repository structure

### ISSUE THREAD

**Issue by schickling** [prisma/specs#54]
See private [Notion document](https://www.notion.so/prismaio/Github-Repo-Split-3fd84ae23b364dacb2aae9cbc78f9aef#7d1f4dbef31740afa165378ada3aa315)

**Comment by janpio** [comment]
@schickling posted on PR:

> Questions this spec should answer:
> 
> * Where does which (code) part of Prisma live? (e.g. query engine, Photon.js generator, ...)
> * Where should a user open an GitHub issue?
> 
> More notes:
> 
> * It probably would help to have some kind of "diagram" which maps out the landscape of repositories.

https://github.com/prisma/specs/pull/85#issuecomment-523877672
