### ISSUE TITLE
Open questions for `init` flow

### ISSUE THREAD

**Issue by nikolasburk** [prisma/specs#55]
We need to address the following open questions for the CLI Init flow.

[See the CLI spec here.](https://prisma-specs.netlify.com/cli/init/)

## Open Questions

- [ ] Preserve scrollablity (e.g. `docker-compose`)
- [ ] Single terminal dev mode
- [ ] Sync between CLI/Studio
- [ ] `--no-colors` / `PRISMA_CLI_NO_COLORS` to disable colors
- [ ] progress indicator for entire flow / step counter (e.g. step 2/6); since steps are dynamic based on selection, how can the progress be calculcated?
- [x] figure out "generated example" after introspection with existing DB

**Comment by nikolasburk** [comment]
- [ ] how does infinite scroll work?

**Comment by janpio** [comment]
`init` has been reworked fundamentally, which will be release with `2.0.0-preview020`. The things mentioned above do not apply to this new command any more.
