### ISSUE TITLE
Document current Prisma "SDK" implementation

### ISSUE THREAD

**Issue by schickling** [prisma/specs#6]

**Comment by janpio** [comment]
"Document" in this case probably means "Specify", correct?

**Comment by schickling** [comment]
This case is a little bit special. We first want to document (aka write down as is) the current state of the Prisma SDK. Based on this "retroactive spec" and more requirements we'll go ahead and "properly" design the Prisma SDK (API, architecture, ...).

Next step: @timsuchanek to write down the current state of the SDK implementation.
