### ISSUE TITLE
Version File Header Generation

### ISSUE THREAD

**Issue by chrisui** [prisma/specs#61]
For debugging purposes it'd be incredibly helpful for, at runtime generation time (ie. `prisma2 generate`) a block comment header to be written to the top of every file with the version of prisma. Also good to have a warning that the file was generated and to modify at own risk!! :)

Bonus: Could also show the migration version the generation is tied to?

**Comment by Jolg42** [comment]
Hello there!
So it's been a while and we have now in the `@prisma/client` (JS client) in `.prisma/client/index.js` after running `npx prisma generate`

```js
/**
 * Prisma Client JS version: 2.0.0-alpha.1233
 * Query Engine version: 4fc8a3eb456e5ff576c77aa830093e34f503f629
 */
exports.prismaVersion = {
  client: "2.0.0-alpha.1233",
  engine: "4fc8a3eb456e5ff576c77aa830093e34f503f629"
}
```
So you can have use it like this:
`import { PrismaClient, prismaVersion} from "@prisma/client";`
