### ISSUE TITLE
Binary spec adjustments

### ISSUE THREAD

**Issue by schickling** [prisma/specs#62]
- [x] Transport (FFI/HTTP)
- [x] Document two use cases for binary fetching and runtime
  - CLI: Fetching (CLI install time), runtime (CLI usage)
  - Generator: Fetching (generation time), runtime (execution for generated artifact)
- [x] Platform overriding/fallback for CLI install (e.g. Lift) - depends on #64 
- [x] Consistent naming convention for all binaries
- [x] Make more consistent
- [x] Link to deployment platform examples
- [x] Generator: Link to generator spec for binary dependencies
- [x] Add a note on copy behavior of custom binary platforms vs known binary platforms
- [x] Error handling

Dependent:

- [ ] https://github.com/prisma/lift/issues/87

**Comment by divyenduz** [comment]
Related issue: https://github.com/prisma/prisma2/issues/337

**Comment by divyenduz** [comment]
Notes:

>  Consistent naming convention for all binaries
In generators yes, in CLI, since we just override it with an env var, no.

**Comment by divyenduz** [comment]
I believe all of this is merged with the latest binary spec.
