### ISSUE TITLE
Create spec for CLI installation

### ISSUE THREAD

**Issue by schickling** [prisma/specs#64]
- Platforms
  - `curl`
  - NPM
  - `go get`
  - Homebrew
  - Apt
  - Docker
  - Installed via Prisma Studio Desktop
  - Windows
	- chocolatey
	- scoop
  - ...
- Considerations
  - Post install script (success screen, telemetry, ...)
  - Self upgrade command
  - Branches/channels/tags

**Comment by janpio** [comment]
Could also mention and explain the npm based installation methods (`npm install -g`, `npx`, `npm install`) and their individual benefits or disadvantages and why we are recommending one of the other
