### ISSUE TITLE
Spec spec

### ISSUE THREAD

**Issue by janpio** [prisma/specs#65]
We need to define what a spec is, what goals it has, who its intended consumers are, what level of depth we expect, how it should be structured etc.

**Comment by schickling** [comment]
Thoughts:

- Purpose of spec files, issues & PRs
- Guidelines for editing issue comments

**Comment by janpio** [comment]
> * Guidelines for editing issue comments

Context? Don't understand.

Thoughts from my side:
- Future facing vs. implemented
- Product vs. Engineering
- Spec vs. Product repos (Crosslinking, moving, ...)

**Comment by schickling** [comment]
Questions this spec should answer:

- Where does which (code) part of Prisma live? (e.g. query engine, Photon.js generator, ...)
- Where should a user open an GitHub issue?

More notes:

- It probably would help to have some kind of "diagram" which maps out the landscape of repositories.

**Comment by janpio** [comment]
(Wrong issue I guess, should probably have been a comment to #85?)
