### ISSUE TITLE
Design (Iterate on) Prisma SDK

### ISSUE THREAD

**Issue by schickling** [prisma/specs#87]
Once we have some initial documentation of the current Prisma SDK implementation (see prisma/specs#6), we should iterate on the API design and collect more use cases.

**Comment by schickling** [comment]
Blocked by https://github.com/prisma/specs/issues/6

**Comment by jasonkuhrt** [comment]
Will there be a Prisma SDK for each language? When we say Prisma SDK right now, are we implicitly saying Prisma Node SDK?

**Comment by janpio** [comment]
@jasonkuhrt A datapoint: The folder in this repo where some stuff from that rough topic is collected currently is named `sdk-js`.
