### ISSUE TITLE
Move over existing RFCs

### ISSUE THREAD

**Issue by schickling** [prisma/specs#9]
- [x] PhotonGo https://github.com/prisma/rfcs/pull/20
- [x] Prisma Schema https://github.com/prisma/rfcs/pull/19
- [x] Migrations https://github.com/prisma/rfcs/pull/10
- [x] Generators https://github.com/prisma/rfcs/pull/4
- [x] Aggregations https://github.com/prisma/rfcs/pull/6
- [x] Expression https://github.com/prisma/rfcs/pull/3

**Comment by matthewmueller** [comment]
migrated
