### ISSUE TITLE
Photon generator language field

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/specs#96]
Originally mentioned in slack [here](https://prisma-company.slack.com/archives/CEYCG2MCN/p1566352965398600).

Seems to me that instead of:

```
generator photon {
  provider = "photonjs"
}
```

it would be more natural as:

```
generator photon {
  provider = "photon"
  language = "js" 
}
```

I think it would be confusing to get into a situation like:

```
generator photon {
  provider = "photonjs"
}
```
```
generator photon {
  provider = "photongo"
}
```
```
generator photon {
  provider = "photonpy"
}
```
```
generator photon {
  provider = "photonhs"
}
```
because:

- photon is a concept in its own right and should be something consistent and stable. We lose that here, as if there are `n` totally different generators when really they are related by the photon principals/patterns which cut across targets. tl;dr we're missing an opportunity to build the right mental model for our users
- the language photon is set to target is intuitively a parameter, but that is lost here
- we probably lose or degrade or complicate autocompletion this way

**Comment by jasonkuhrt** [comment]
@schickling should we close this one? I like it but IIUC it has been decided otherwise previously right?

**Comment by schickling** [comment]
We thought of this but decided against a photon generator with a `language` option but making them completely separate generators (e.g. `photonjs`).
