### ISSUE TITLE
CLI `init`: Support PostgreSQL database creation + simplify spec

### ISSUE THREAD

**Issue by nikolasburk** [prisma/specs#98]
The current spec for the `prisma2 init` flow needs some cleanup. Here are a few notes about the _current_ state of the spec:

The current version on `master` contains a coherent version of the `init` flow. This is the version that we are currently implementing and that's expected to be released in `preview-9`. 

It's important to note that in this version, the flow for PostgreSQL does not help with detecting/creating a _PostgreSQL database_, this means there will always be an error when a user doesn't know to which database they want to connect. This is not the ideal user experience and we want to optimize this later (i.e. help the user figure out which database to use or to create a new one similar). It does help with detecting/creating a _PostgreSQL schema_ though. 

There's currently another branch called `linearize-init`. The goal of this branch was to simplify the flow diagrams and the page structure to make the spec easier to consume. However, it also already contains the UX optimization where we want to help users figure out which PostgreSQL database to use or create a new one. This makes the PostgreSQL flow a lot more complex.

Because we're currently implementing the simpler version of the spec and need to move on to other important things, we leave the `linearize-init` branch unfinished and merge it after `preview-9` was released. We'll eventually finish up the spec when we also want to tackle _implementing_ the UX optimization.

The purpose of this issue is to provide some context for the time when the work on the UX optimization is picked up again and it should be left open until then. Here's the state of the different paths through the `init` flow:

- Starter kit
  - SQLite: ✅
  - MySQL: ✅
  - PostgreSQL: Not started
- Blank project
  - SQLite: ✅
  - MySQL: ✅
  - PostgreSQL: Started but needs more work

**Comment by janpio** [comment]
`init` has been reworked fundamentally, which will be release with `2.0.0-preview020`. The things mentioned above do not apply to this new command any more.
